Repository dvsa/cvs-app-vtm, pull requests merged in 2020-02, with the labels that each got.

#74 Feature/cvsb 11349
  cypress/integration/7239.ACs.spec.ts
  cypress/integration/9213.ACs.spec.ts
  package.json
  sonar-project.properties
  src/app/adr-details-form/adr-details-form.component.html
  src/app/adr-details-form/adr-details-form.spec.ts
  src/app/adr-details-form/store/adrDetails.actions.spec.ts
  src/app/adr-details-form/store/adrDetails.reducer.spec.ts
  src/app/adr-details-form/store/adrDetails.reducer.ts
  src/app/adr-details-form/store/adrDetailsMockObjects.ts
  src/app/adr-details-form/store/download-documents.effects.ts
  src/app/pipes/FilterRecordPipe.spec.ts
  src/app/pipes/IsPrimaryVrmPipe.spec.ts
  src/app/pipes/OrderByStatusPipe.spec.ts
  src/app/pipes/keysPipe.spec.ts
  src/app/shell/header/header.component.spec.ts
  src/app/shell/header/header.component.ts
  src/app/store/actions/VehicleTechRecordModel.actions.spec.ts
  src/app/store/actions/VehicleTestResultModel.actions.spec.ts
  src/app/store/actions/VehicleTestResultModel.actions.ts
  src/app/store/reducers/VehicleTechRecordModel.reducers.spec.ts
  src/app/store/reducers/VehicleTestResultModel.reducers.spec.ts
  src/app/store/selectors/route.selectors.spec.ts
  src/app/store/selectors/searchPage.selectors.spec.ts
  src/app/technical-record-search/auth-token-interceptor.spec.ts
  src/app/technical-record-search/technical-record-search.component.spec.ts
  src/app/technical-record-search/technical-record.service.spec.ts
  src/app/technical-record-search/technical-record.service.ts
  src/app/technical-record-search/test-result.service.spec.ts
  src/app/technical-record/store/adrDetailsSubmit.actions.spec.ts
  src/app/technical-record/store/adrDetailsSubmit.reducer.spec.ts
  src/app/technical-record/store/adrDetailsSubmit.reducer.ts
  src/app/technical-record/technical-record.component.html
  src/app/technical-record/technical-record.component.spec.ts
  src/app/technical-record/technical-record.component.ts
  testconfig/services-mocks/authentication-guard.mock.spec.ts
  testconfig/services-mocks/technical-record-service.mock.spec.ts
  testconfig/services-mocks/technical-record-service.mock.ts
  testconfig/test-store.ts
Labels: coverage, require code review

#79 CVSB-11845 Fixed sensing value field show
  src/app/technical-record/technical-record.component.html
Labels: bug, require code review

#85 Feature/cvsb-10856
  src/app/app.module.ts
  src/app/shared/pending-changes-guard/pending-changes.guard.spec.ts
  src/app/shared/pending-changes-guard/pending-changes.guard.ts
  src/app/shared/pending-changes-service/pending-changes.service.spec.ts
  src/app/shared/pending-changes-service/pending-changes.service.ts
  src/app/shared/prevent-page-leave-modal/prevent-leave-page-modal.component.html
  src/app/shared/prevent-page-leave-modal/prevent-leave-page-modal.component.scss
  src/app/shared/prevent-page-leave-modal/prevent-leave-page-modal.component.spec.ts
  src/app/shared/prevent-page-leave-modal/prevent-leave-page-modal.component.ts
  src/app/shared/shared.module.ts
  src/app/technical-record/adr-details/adr-details-form/store/adrDetails.actions.spec.ts
  src/app/technical-record/technical-record.component.spec.ts
  src/app/technical-record/technical-record.component.ts
  src/app/technical-record/technical-record.module.ts
Labels: enhancement
