Repository dvsa/cvs-app-vtm, pull requests merged in 2022-09, with the labels that each got.

#486 feat(cb2-5625): defects service design
  src/app/features/search/multiple-search-results/multiple-search-results.component.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/components/result-of-test/result-of-test.component.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/forms/components/defect-select/defect-select.component.html
  src/app/forms/components/defect-select/defect-select.component.scss
  src/app/forms/components/defect-select/defect-select.component.spec.ts
  src/app/forms/components/defect-select/defect-select.component.ts
  src/app/forms/components/defect/defect.component.html
  src/app/forms/components/defect/defect.component.scss
  src/app/forms/components/defect/defect.component.spec.ts
  src/app/forms/components/defect/defect.component.ts
  src/app/forms/components/defects/defects.component.html
  src/app/forms/components/defects/defects.component.spec.ts
  src/app/forms/components/defects/defects.component.ts
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/radio-group/radio-group.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.service.spec.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/guards/cancel-edit-test/cancel-edit-test.guard.spec.ts
  src/app/guards/cancel-edit-test/cancel-edit-test.guard.ts
  src/app/shared/components/tag/tag.component.ts
  src/app/shared/pipes/truncate/truncate.pipe.spec.ts
  src/app/shared/pipes/truncate/truncate.pipe.ts
  src/app/store/defects/selectors/defects.selectors.spec.ts
  src/app/store/defects/selectors/defects.selectors.ts
  src/app/store/test-records/actions/test-records.actions.ts
  src/app/store/test-records/reducers/test-records.reducer.spec.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
  src/app/store/test-records/selectors/test-records.selectors.spec.ts
Labels: enhancement

#508 feat(cb2-5340): collapsible sections
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.html
  src/app/forms/templates/general/defect.template.ts
  src/app/forms/templates/test-records/section-templates/customDefects/custom-defects-section.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/notes/notes-section.template.ts
  src/app/forms/templates/test-records/section-templates/reasonForCreation/resonForCreation.template.ts
  src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts
  src/app/shared/components/accordion-control/accordion-control.component.html
  src/app/shared/components/accordion-control/accordion-control.component.spec.ts
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/shared/components/accordion/accordion.component.html
  src/app/shared/components/accordion/accordion.component.scss
  src/app/shared/components/accordion/accordion.component.spec.ts
  src/app/shared/components/accordion/accordion.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#505 test(cb2-5882): add in effect tests
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: coverage

#498 feat(cb2-5808): allowing creation of contingency tests for trailers
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/required/contingency-required-hidden-section-hgv-trl.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
Labels: enhancement

#506 fix(*): loading overlay
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/core/components/spinner/spinner.component.html
  src/app/core/components/spinner/spinner.component.spec.ts
  src/app/core/components/spinner/spinner.component.ts
  src/app/features/tech-record/tech-record.component.html
  src/app/features/tech-record/tech-record.component.spec.ts
  src/app/features/tech-record/tech-record.component.ts
  src/app/services/loading/loading.service.spec.ts
  src/app/services/loading/loading.service.ts
Labels: bug

#502 feat(cb2-5728): auto focus date segments
  src/app/forms/components/date/date.component.html
  src/app/forms/components/date/date.component.ts
  src/app/forms/components/date/focus-next.directive.spec.ts
  src/app/forms/components/date/focus-next.directive.ts
  src/app/forms/dynamic-forms.module.ts
Labels: enhancement

#507 fix(*): handle unknown routes
  src/app/app-routing.module.ts
  src/app/core/components/page-not-found/page-not-found.component.html
  src/app/core/components/page-not-found/page-not-found.component.spec.ts
  src/app/core/components/page-not-found/page-not-found.component.ts
  src/app/core/core.module.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
Labels: bug

#509 test(CB2-6125): improve VTM test coverage
  src/app/app.component.spec.ts
  src/app/core/components/breadcrumbs/breadcrumbs.component.spec.ts
  src/app/core/components/global-error/global-error.service.spec.ts
  src/app/directives/app-role-required.directive.spec.ts
  src/app/directives/app-role-required.directive.ts
  src/app/features/search/search.component.html
  src/app/features/search/search.component.spec.ts
  src/app/features/search/search.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record.component.html
  src/app/features/tech-record/tech-record.component.spec.ts
  src/app/features/tech-record/tech-record.component.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/forms/components/date/date.component.spec.ts
  src/app/forms/components/defects/defects.component.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/mocks/trl-record.mock.ts
Labels: coverage

#510 fix(cb2-6113): handle duplicate system numbers in tech record db
  src/app/app-routing.module.ts
  src/app/features/search/single-search-result/single-search-result.component.ts
  src/app/forms/templates/search/single-search-result.template.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: bug
