Repository dvsa/cvs-app-vtm, pull requests merged in 2022-11, with the labels that each got.

#627 fix(cb2-6524 & cb2-6523): amend maufactureyear and eurostandard form validation
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#628 fix(cb2-5702): rewrite the dimensions templates
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.html
  src/app/forms/custom-sections/dimensions/dimensions.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/dimensions.template.ts
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
  src/app/forms/templates/psv/psv-dimensions.template.ts
  src/app/forms/templates/trl/trl-dimensions.template.ts
Labels: bug

#629 feat(cb2-5857): added back button
  src/app/features/test-records/amend/views/test-record/test-record.component.html
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.html
  src/app/forms/custom-sections/defect/defect.component.html
  src/app/forms/custom-sections/defects/defects.component.html
  src/app/shared/components/button/button.component.scss
Labels: enhancement

#634 fix(cb2-6474): fix reasons for abandoning
  src/app/forms/components/checkbox-group/checkbox-group.component.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.spec.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.ts
  src/app/forms/services/multi-options.service.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/models/reference-data.model.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/actions/reference-data.actions.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
  src/mocks/reference-data/mock-hgv-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-psv-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-trl-reasons-for-abandoning.reference-data.ts
Labels: bug

#633 fix(cb2-6509): fix validation on vehicle summary
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#632 feat(cb2-3782): comma delimited formatting
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.spec.ts
  src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#624 Feat(cb2-5700): Amend PSV, HGV & TRL Tyres section
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/general/tyres.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tyres.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tyres.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/templates/trl/trl-tyres.template.ts
  src/app/forms/utils/enum-map.ts
  src/app/models/reference-data.model.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/mocks/reference-data/mock-tyres.ts
Labels: enhancement

#636 feat(cb2-5614): handle 500 failures
  src/app/app-routing.module.ts
  src/app/core/components/server-error/server-error.component.html
  src/app/core/components/server-error/server-error.component.spec.ts
  src/app/core/components/server-error/server-error.component.ts
  src/app/core/core.module.ts
  src/app/interceptors/error-handling/error-handling.interceptor.spec.ts
  src/app/interceptors/error-handling/error-handling.interceptor.ts
  src/app/interceptors/error-handling/error-handling.module.ts
  src/app/interceptors/interceptor.module.ts
  src/app/store/test-records/effects/test-records.effects.ts
Labels: enhancement

#637 feat(cb2 5693): Amend PSV Body section
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/components/select/select.component.scss
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/custom-sections/body/body.component.scss
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/templates/hgv/hgv-trl-body.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/models/body-type-enum.ts
  src/app/models/reference-data.model.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/mocks/reference-data/mock-psv-make.reference-data.ts
Labels: enhancement, help wanted, require code review, sprint goal

#640 fix(cb2-6474): fix the reasons for abandoning
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.ts
Labels: bug

#635 feat(cb2-5690): implement the hgv & trl brakes section
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/components/autocomplete/autocomplete.component.html
  src/app/forms/components/autocomplete/autocomplete.component.scss
  src/app/forms/components/autocomplete/autocomplete.component.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/components/number-input/number-input.component.scss
  src/app/forms/components/number-input/number-input.component.ts
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/text-input/text-input.component.scss
  src/app/forms/components/text-input/text-input.component.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.scss
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.spec.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.html
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.scss
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.spec.ts
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.ts
  src/app/forms/directives/prefix.directive.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/psv/psv-brakes.template.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/models/reference-data.model.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
  src/mocks/psv-record.mock.ts
  src/mocks/reference-data/mock-brakes.ts
Labels: enhancement

#647 fix(cb2-6613): fix the notes section not displaying
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#648 fix custom defects
  src/app/features/test-records/amend/views/test-record/test-record.component.html
  src/app/forms/custom-sections/custom-defect/custom-defect.component.html
  src/app/forms/custom-sections/custom-defects/custom-defects.component.html
Labels: bug

#649 refactor(cb2-5690): remove the 2 extra brake force sections
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/templates/psv/psv-brake-wheels-half-locked.template.ts
  src/app/forms/templates/psv/psv-brake-wheels-not-locked.template.ts
Labels: bug

#650 feat(cb2-6625): adds TestResult.CreateContingency permission
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/models/roles.enum.ts
Labels: enhancement

#652 fix(cb2-6642): check the right weights property
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#644 feat(cb2-6092): hide emissions section
  src/app/forms/models/async-validators.enum.ts
  src/app/forms/models/condition.model.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
  src/app/forms/validators/custom-async-validators.spec.ts
  src/app/forms/validators/custom-async-validators.ts
Labels: enhancement

#651 bumps VTM version number to 1.2.0 for release
  package-lock.json
  package.json
Labels: enhancement

#656 feat(cb2-6502): psv lec contingency test without linked
  src/app/forms/models/testTypeId.enum.ts
Labels: enhancement

#657 feat(cb2-5710): update the plates section to the clients standard
  src/app/forms/components/select/select.component.scss
  src/app/forms/templates/general/plates.template.ts
Labels: enhancement

#661 fix(cb2-6661): adding defect to new test result returns back to technical record
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.spec.ts
  src/app/shared/components/button/button.component.html
  src/app/shared/components/button/button.component.spec.ts
  src/app/shared/components/button/button.component.ts
Labels: bug

#654 feat(cb2-6468): fetch reference data
  src/app/api/reference-data/.gitignore
  src/app/api/reference-data/.npmignore
  src/app/api/reference-data/.swagger-codegen-ignore
  src/app/api/reference-data/.swagger-codegen/VERSION
  src/app/api/reference-data/api.module.ts
  src/app/api/reference-data/api/api.ts
  src/app/api/reference-data/api/referenceData.service.ts
  src/app/api/reference-data/configuration.ts
  src/app/api/reference-data/encoder.ts
  src/app/api/reference-data/git_push.sh
  src/app/api/reference-data/index.ts
  src/app/api/reference-data/model/deleteItem.ts
  src/app/api/reference-data/model/emptyObject.ts
  src/app/api/reference-data/model/models.ts
  src/app/api/reference-data/model/referenceDataApiResponse.ts
  src/app/api/reference-data/model/referenceDataApiResponseWithPagination.ts
  src/app/api/reference-data/model/referenceDataApiResponseWithoutPagination.ts
  src/app/api/reference-data/model/referenceDataItem.ts
  src/app/api/reference-data/model/referenceDataItemApiResponse.ts
  src/app/api/reference-data/model/resourceKey.ts
  src/app/api/reference-data/ng-package.json
  src/app/api/reference-data/variables.ts
  src/app/app.module.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/models/reference-data.model.ts
  src/app/services/reference-data/reference-data.service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/actions/reference-data.actions.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.ts
  src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
  src/mocks/reference-data/mock-TIR-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-hgv-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-psv-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-specialist-reasons-for-abandoning.reference-data.ts
  src/mocks/reference-data/mock-trl-reasons-for-abandoning.reference-data.ts
Labels: enhancement

#662 feat(CB2-6091): enable amend certificate and anniversary date
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#663 feat(cb2-5337): multi column layout for tech records
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.scss
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.scss
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.scss
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/shared/components/accordion-control/accordion-control.component.html
  src/app/shared/components/accordion-control/accordion-control.component.scss
  src/app/shared/components/accordion-control/accordion-control.component.ts
Labels: enhancement

#666 fix(cb2-6683): fix amending provisional record
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#667 feat(cb2-6669): implement the provisional promotion workflow
  src/app/features/tech-record/components/tech-promote/tech-promote.component.html
  src/app/features/tech-record/components/tech-promote/tech-promote.component.spec.ts
  src/app/features/tech-record/components/tech-promote/tech-promote.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group15and16.template.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#677 feat(cb2-6718): added snyk
  .github/workflows/ci.yml
Labels: enhancement

#678 fix(cb2-6669): make the reason for promotion required
  src/app/features/tech-record/components/tech-promote/tech-promote.component.html
  src/app/features/tech-record/components/tech-promote/tech-promote.component.ts
Labels: bug

#660 feat(cb2-5341): input widths
  src/app/forms/templates/test-records/section-templates/customDefects/custom-defects-section.template.ts
  src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group12and14.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts
  src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts
Labels: enhancement

#673 feature(cb2 6415): lookup tyres data
  src/app/api/reference-data/.swagger-codegen/VERSION
  src/app/api/reference-data/api/referenceData.service.ts
  src/app/features/tech-record/components/tech-promote/tech-promote.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/tyres-search/tyres-search.component.html
  src/app/features/tech-record/components/tyres-search/tyres-search.component.scss
  src/app/features/tech-record/components/tyres-search/tyres-search.component.spec.ts
  src/app/features/tech-record/components/tyres-search/tyres-search.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/tyres/tyres.component.scss
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/models/reference-data.model.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/reference-data/reference-data.service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/shared/components/pagination/pagination.component.ts
  src/app/store/reference-data/actions/reference-data.actions.spec.ts
  src/app/store/reference-data/actions/reference-data.actions.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.ts
  src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement, require code review, sprint goal

#682 feat(cb2-6502): contingency test lec psv
  src/app/forms/templates/test-records/create-master.template.ts
Labels: bug, documentation, enhancement, help wanted, invalid/duplicate, question, coverage, old/no info, dependencies

#685 feat(cb2-6764): add role guards to new permission
  src/app/features/tech-record/components/tech-promote/tech-promote.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/models/roles.enum.ts
Labels: enhancement

#686 fix(CB2-5695): Amend PSV Vehicle Summary section for provisional record
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
  src/app/forms/templates/psv/psv-tech-record.template.ts
Labels: enhancement

#687 fix(cb2-6768): add noOfAxles to psv and trl
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#694 feature(cb2-6684): update the trl suspension type to a dropdown
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#695 fix(*): add route for tyre search when amending provisional
  src/app/features/tech-record/tech-record-routing.module.ts
Labels: bug

#698 fix(CB2-6814): Tyre search criteria gets cleared after search result displayed
  src/app/core/components/header/header.component.html
  src/app/features/tech-record/components/tyres-search/tyres-search.component.html
  src/app/features/tech-record/components/tyres-search/tyres-search.component.spec.ts
  src/app/features/tech-record/components/tyres-search/tyres-search.component.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/actions/reference-data.actions.spec.ts
  src/app/store/reference-data/actions/reference-data.actions.ts
  src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
Labels: enhancement

#701 Feat(cb2-6547): create a psv desk based Test Group 4
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group4.template.ts
  src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts
Labels: enhancement

#710 Create a PSV desk based Test Group 2 -fix
  src/app/forms/templates/test-records/section-templates/test/desk-based-test-section-group2-PSV.template.ts
Labels: enhancement

#702 refactor(cb2-6727): refactored role directive to take array or single
  src/app/directives/app-role-required.directive.spec.ts
  src/app/directives/app-role-required.directive.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/models/roles.enum.ts
  src/app/store/test-types/effects/test-types.effects.ts
Labels: bug

#709 feat(CB2-6532): Amend PSV desk based test group 2
  src/app/forms/templates/test-records/master.template.ts
Labels: enhancement

#714 feat(CB2-6532): Amend PSV Desk Based Tests Group 2
  src/app/forms/templates/test-records/master.template.ts
Labels: enhancement

#704 feat(cb2-5819): create group 1 hgv/trl template
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based-test-group1-HGV-TRL.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
Labels: enhancement

#718 bug(CB2-6891): Contingency Tests - Add default values for 2 fields
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
Labels: bug

#719 fix(cb2 6887): add alteration marker to psv tech record, and hide value when not in amend
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug
