Repository dvsa/cvs-app-vtm, pull requests merged in 2022-10, with the labels that each got.

#522 fix(cb2-5725): navigate back when state refreshed
  src/app/forms/components/defect/defect.component.html
  src/app/forms/components/defect/defect.component.ts
Labels: bug

#529 fix(cb2-6192): navigate on cancelling amendment of tech record
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
Labels: bug

#527 feat(cb2-5688): use accordions in tech summary and add custom dimensions
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.scss
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/components/dimensions/dimensions.component.html
  src/app/forms/components/dimensions/dimensions.component.scss
  src/app/forms/components/dimensions/dimensions.component.spec.ts
  src/app/forms/components/dimensions/dimensions.component.ts
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.html
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.spec.ts
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/applicant-details.template.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/general/axle-weights.template.ts
  src/app/forms/templates/general/body.template.ts
  src/app/forms/templates/general/dimensions.template.ts
  src/app/forms/templates/general/documents.template.ts
  src/app/forms/templates/general/gross-vehicle-weights.template.ts
  src/app/forms/templates/general/notes.template.ts
  src/app/forms/templates/general/plates.template.ts
  src/app/forms/templates/general/resonForCreation.template.ts
  src/app/forms/templates/general/tyres.template.ts
  src/app/forms/templates/hgv/hgv-brakes.template.ts
  src/app/forms/templates/hgv/hgv-gross-train-weights.template.ts
  src/app/forms/templates/hgv/hgv-max-train-weights.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-brake-wheels-half-locked.template.ts
  src/app/forms/templates/psv/psv-brake-wheels-not-locked.template.ts
  src/app/forms/templates/psv/psv-brake.template.ts
  src/app/forms/templates/psv/psv-dda.template.ts
  src/app/forms/templates/psv/psv-notes.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/psv/psv-train-weight.template.ts
  src/app/forms/templates/trl/trl-auth-into-service.template.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/forms/templates/trl/trl-manufacturer.template.ts
  src/app/forms/templates/trl/trl-purchaser.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#525 feat(cb2-5692): amend PSV weights section for provisional record
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/components/weights/weights.component.html
  src/app/forms/components/weights/weights.component.spec.ts
  src/app/forms/components/weights/weights.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/general/axle-weights.template.ts
  src/app/forms/templates/general/gross-vehicle-weights.template.ts
  src/app/forms/templates/general/weights.template.ts
  src/app/forms/templates/hgv/hgv-gross-train-weights.template.ts
  src/app/forms/templates/hgv/hgv-max-train-weights.template.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/psv/psv-train-weight.template.ts
  src/app/forms/templates/psv/psv-weight.template.ts
  src/app/forms/templates/trl/trl-weight.template.ts
Labels: enhancement

#532 feat(cb2-5779): added specialist test group 1
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/required-hidden-specialist-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
Labels: enhancement

#539 fix(cb2-6223): fix max and min length validation message
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
Labels: bug

#528 feat(cb2-3798): contingency testing psv voluntary and notifiable alterations test
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
Labels: enhancement

#540 fix(cb2-6229): only toggle edit mode when form is valid
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
Labels: bug

#521 feat(cb2-6177): tech record history pagination
  src/app/app-routing.module.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/shared/components/accordion-control/accordion-control.component.scss
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/shared/components/pagination/pagination.component.html
  src/app/shared/components/pagination/pagination.component.scss
  src/app/shared/components/pagination/pagination.component.spec.ts
  src/app/shared/components/pagination/pagination.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#542 chore(*): add service design to last applicant
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/templates/general/applicant-details.template.ts
  src/app/forms/templates/general/manufacturer.template.ts
Labels: enhancement

#546 fix(cb2-6237): add validation to tech summary dimensions
  src/app/forms/components/dimensions/dimensions.component.ts
  src/app/forms/templates/general/dimensions.template.ts
  src/app/forms/utils/error-message-map.ts
Labels: bug

#545 feature(CB2-5701): Create the TRL Brakes Component
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/forms/components/autocomplete/autocomplete.component.html
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/brakes/brakes.component.html
  src/app/forms/components/brakes/brakes.component.scss
  src/app/forms/components/brakes/brakes.component.spec.ts
  src/app/forms/components/brakes/brakes.component.ts
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.ts
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/components/number-input/number-input.component.ts
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/radio-group/radio-group.component.ts
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/text-input/text-input.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/manufacturer.template.ts
  src/app/forms/templates/psv/psv-brake.template.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/shared/components/pagination/pagination.component.ts
Labels: enhancement

#549 fix(cb2-6224): fix accordion icons and toggling functionality
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/shared/components/accordion-control/accordion-control.component.html
  src/app/shared/components/accordion-control/accordion-control.component.spec.ts
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/shared/components/accordion/accordion.component.html
  src/app/shared/components/accordion/accordion.component.spec.ts
  src/app/shared/components/accordion/accordion.component.ts
Labels: bug

#536 feat(cb2-5699): create TRL and HGV weight sections
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/components/number-input/number-input.component.ts
  src/app/forms/components/weights/weights.component.html
  src/app/forms/components/weights/weights.component.spec.ts
  src/app/forms/components/weights/weights.component.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/psv/psv-weight.template.ts
  src/app/forms/templates/trl/trl-weight.template.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: enhancement

#550 Simplify calculation of pagination visible pages
  src/app/shared/components/pagination/pagination.component.ts
Labels: enhancement

#547 fix(cb2-5725): fixed removing defect
  src/app/forms/components/defect/defect.component.html
  src/app/forms/components/defect/defect.component.ts
Labels: bug

#555 fix(cb2-3798): removed PRS from template
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
Labels: bug

#553 fix(cb2-6250): fixed collapsible sections
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
Labels: bug

#541 feat(cb2-6203): added contingency support for free loaded trl test
  src/app/forms/models/testTypeId.enum.ts
Labels: enhancement

#558 fix(*): fix input bar width service design
  src/app/forms/components/text-input/text-input.component.ts
  src/app/forms/templates/general/applicant-details.template.ts
Labels: bug

#557 fix(cb2-6266): removed redundant code and fixed advisory defects
  src/app/forms/components/defect-select/defect-select.component.ts
  src/app/forms/components/defects/defects.component.spec.ts
  src/app/forms/components/defects/defects.component.ts
  src/app/store/defects/selectors/defects.selectors.ts
Labels: bug

#561 fix(cb2-5701): add a dropdown component and pascal case brake titles
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/forms/components/brakes/brakes.component.html
  src/app/forms/components/brakes/brakes.component.ts
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.scss
  src/app/forms/components/select/select.component.ts
  src/app/forms/components/weights/weights.component.spec.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/models/options.model.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/shared/components/pagination/pagination.component.html
Labels: bug, enhancement, coverage

#563 feat(cb2-5707): added trl purchase validation
  src/app/forms/templates/trl/trl-purchaser.template.ts
Labels: enhancement

#564 feat(cb2-5880): sorting tests chronologically
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.stories.ts
Labels: enhancement

#566 feat(cb2-6208): amend start and end time
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts
Labels: enhancement

#556 add govuk icon
  src/assets/icon/favicon.ico
  src/favicon.ico
  src/index.html
Labels: enhancement

#565 fix(cb2-6291): fix displaying string booleans
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/shared/pipes/default-null-or-empty/default-null-or-empty.pipe.ts
Labels: bug

#567 feat(cb2-5706): add date type to edit and process format
  src/app/forms/components/date/date.component.html
  src/app/forms/components/date/date.component.spec.ts
  src/app/forms/components/date/date.component.ts
  src/app/forms/components/date/focus-next.directive.spec.ts
  src/app/forms/components/date/focus-next.directive.ts
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/trl/trl-auth-into-service.template.ts
  src/app/forms/validators/date/date.validators.spec.ts
  src/app/forms/validators/date/date.validators.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#568 feat(cb2-5881): modify vehicle details header
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
Labels: enhancement

#573 feat(cb2-4817): added contingency tests for specialist group 1
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
Labels: enhancement

#570 feat(CB2-5703): Amend HGV & TRL Type Approval section
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.scss
  src/app/forms/components/select/select.component.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/utils/enum-map.ts
Labels: enhancement

#534 task(*): input suffix directive
  package-lock.json
  src/app/forms/components/autocomplete/autocomplete.component.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/dimensions/dimensions.component.html
  src/app/forms/components/dimensions/dimensions.component.spec.ts
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.html
  src/app/forms/components/number-input-with-suffix/number-input-with-suffix.component.ts
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/components/read-only/read-only.component.html
  src/app/forms/components/read-only/read-only.component.spec.ts
  src/app/forms/components/read-only/read-only.component.ts
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/components/view-list-item/view-list-item.component.ts
  src/app/forms/components/weights/weights.component.html
  src/app/forms/components/weights/weights.component.spec.ts
  src/app/forms/directives/suffix/suffix.directive.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/shared/components/pagination/pagination.component.spec.ts
Labels: enhancement

#548 feat(cb2-6206): specialist group 3
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3.template.ts
Labels: enhancement

#578 feat(cb2-6092): hide emissions section
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/forms/models/async-validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-async-validators.spec.ts
  src/app/forms/validators/custom-async-validators.ts
Labels: enhancement

#574 chore(*): add more tests for edit tech record button
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
Labels: coverage

#569 feat(cb2-6333): implement a switchable form component
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/brakes/brakes.component.html
  src/app/forms/components/dimensions/dimensions.component.html
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/components/number-input/number-input.component.ts
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/radio-group/radio-group.component.ts
  src/app/forms/components/read-only/read-only.component.html
  src/app/forms/components/read-only/read-only.component.spec.ts
  src/app/forms/components/read-only/read-only.component.ts
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.spec.ts
  src/app/forms/components/select/select.component.ts
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.spec.ts
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/components/text-area/text-area.component.html
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/text-input/text-input.component.ts
  src/app/forms/custom-sections/brakes/brakes.component.html
  src/app/forms/custom-sections/brakes/brakes.component.scss
  src/app/forms/custom-sections/brakes/brakes.component.spec.ts
  src/app/forms/custom-sections/brakes/brakes.component.ts
  src/app/forms/custom-sections/defect/defect.component.html
  src/app/forms/custom-sections/defect/defect.component.scss
  src/app/forms/custom-sections/defect/defect.component.spec.ts
  src/app/forms/custom-sections/defect/defect.component.ts
  src/app/forms/custom-sections/defects/defects.component.html
  src/app/forms/custom-sections/defects/defects.component.spec.ts
  src/app/forms/custom-sections/defects/defects.component.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.html
  src/app/forms/custom-sections/dimensions/dimensions.component.scss
  src/app/forms/custom-sections/dimensions/dimensions.component.spec.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.ts
  src/app/forms/custom-sections/weights/weights.component.html
  src/app/forms/custom-sections/weights/weights.component.spec.ts
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/directives/suffix.directive.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/dimensions.template.ts
Labels: enhancement

#581 fix(cb2-6342): change manufacturer telephone typo
  src/app/forms/templates/general/manufacturer.template.ts
Labels: bug

#579 feat(cb2-4228): amend custom defects
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/forms/custom-sections/custom-defect/custom-defect.component.html
  src/app/forms/custom-sections/custom-defect/custom-defect.component.scss
  src/app/forms/custom-sections/custom-defect/custom-defect.component.spec.ts
  src/app/forms/custom-sections/custom-defect/custom-defect.component.ts
  src/app/forms/custom-sections/custom-defects/custom-defects.component.html
  src/app/forms/custom-sections/custom-defects/custom-defects.component.spec.ts
  src/app/forms/custom-sections/custom-defects/custom-defects.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/shared/components/button/button.component.scss
Labels: enhancement

#583 feat(cb2-6303): update dangerous defect taxonomy
  src/app/forms/components/defect-select/defect-select.component.html
  src/app/forms/custom-sections/defect/defect.component.html
  src/app/forms/custom-sections/defect/defect.component.ts
  src/app/forms/custom-sections/defects/defects.component.html
Labels: enhancement

#562 fix(cb2-6199): removed custom defects/defects field
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/custom-defects-hidden-section.template.ts
  src/app/forms/templates/test-records/section-templates/required/defect-hidden-section.template.ts
  src/app/forms/templates/test-records/section-templates/required/seatbelt-hidden-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group5And13.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group6And11.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group4.template.ts
Labels: bug

#586 feat(cb2-6219): Amending HGV/TRL specialist group 5
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/specialist-required-hidden-section-hgv-trl.template.ts
Labels: enhancement

#588 fix(cb2-5814): fixed validation issue
  src/app/forms/validators/custom-validators.ts
Labels: bug

#587 feat(cb2-6390): start/end date validation
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group12and14.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group5.template.ts
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#591 fix(cb2-4228): added validation
  src/app/forms/templates/test-records/section-templates/customDefects/custom-defects-section.template.ts
Labels: bug

#594 feat/cb2 6303 move asterisk
  src/app/forms/components/defect-select/defect-select.component.html
  src/app/forms/custom-sections/defect/defect.component.html
  src/app/forms/custom-sections/defects/defects.component.html
Labels: enhancement

#593 feat(cb2-4817): added certificate number field to test record
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group1.template.ts
Labels: enhancement

#592 test(*): add tests for error messages
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
Labels: coverage

#576 feat(CB2-5707): Amend TRL Purchaser section for a provisional Tech Record
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/trl/trl-purchaser.template.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: enhancement

#601 feat(cb2-6206): removed disabled true from start/end time
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3.template.ts
Labels: enhancement

#595 feat(CB2-5695): Amend PSV Vehicle Summary section for provisional record
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.scss
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/body.template.ts
  src/app/forms/templates/general/tyres.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/utils/enum-map.ts
Labels: enhancement

#604 feat(cb2-6213): added group 3
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency-test-section-specialist-group4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist-test-section-group3And4.template.ts
Labels: enhancement

#606 feat(cb2-6062) amend a current technical record
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-amend-reason/tech-amend-reason.component.html
  src/app/features/tech-record/components/tech-amend-reason/tech-amend-reason.component.spec.ts
  src/app/features/tech-record/components/tech-amend-reason/tech-amend-reason.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#605 feat(cb2-5702): extend dimensions to cater for hgvs and trls
  src/app/forms/custom-sections/dimensions/dimensions.component.html
  src/app/forms/custom-sections/dimensions/dimensions.component.scss
  src/app/forms/templates/general/dimensions.template.ts
Labels: enhancement

#607 feat(cb2-5817): added group 1 amend
  src/app/forms/templates/test-records/master.template.ts
Labels: enhancement

#614 fix(cb2-6062): added default selection to radio group
  src/app/features/tech-record/components/tech-amend-reason/tech-amend-reason.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: bug

#616 fix(*): clear errors on navigation and stop errors in tech record non-edit mode
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
  src/app/store/global-error/reducers/global-error-service.reducer.ts
Labels: bug

#612 feat(cb2-6248): amend hgv & trl vehicle summary section
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#620 feature(cb2-5704): add the body section for hgv and trl
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.scss
  src/app/forms/components/select/select.component.ts
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/custom-sections/body/body.component.scss
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/custom-sections/brakes/brakes.component.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/multi-options.service.ts
  src/app/forms/templates/general/body.template.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/models/body-type-enum.ts
  src/app/models/reference-data.model.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/mocks/hgv-record.mock.ts
  src/mocks/psv-record.mock.ts
  src/mocks/reference-data/mock-body-makes.ts
  src/mocks/reference-data/mock-body-models.ts
Labels: enhancement

#623 fix(cb2-5702): add the missing validators to the dimensions section
  src/app/forms/templates/general/dimensions.template.ts
Labels: bug

#625 fixed patch value attempting to read null/undefined values
  src/app/forms/services/dynamic-form.types.ts
Labels: bug

#626 feat(cb2-6304): confirm prohibition notice
  src/app/forms/custom-sections/defect/defect.component.html
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/defect.template.ts
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/defects/defect.validators.spec.ts
  src/app/forms/validators/defects/defect.validators.ts
Labels: enhancement
