Repository dvsa/cvs-app-vtm, pull requests merged in 2023-05, with the labels that each got.

#1015 feat(cb2-7927): Euro V
  src/app/models/test-types/emissions.enum.ts
Labels: enhancement

#1014 fix(cb2-8158): updates navigation for reference data
  src/app/app-routing.module.ts
  src/app/features/home/home.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/reference-data/reference-data-routing.module.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.ts
  src/app/forms/components/radio-group/radio-group.component.html
Labels: bug

#1016 fix(cb2-8165): fill in details in create vehicle
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/forms/components/checkbox-group/checkbox-group.component.html
  src/app/forms/components/checkbox/checkbox.component.html
Labels: bug

#1018 fix(cb2-8151): added custom validator to handle input length validati…
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1019 fix(cb2-8161): navigates back nicely on browser refresh
  cypress/e2e/techRecord/HGV/hgv.cy.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1020 fix(cb2-8192): ref-data admin - adds validation for required field 'resourceKey'
  src/app/features/reference-data/reference-data-add/reference-data-add.component.html
  src/app/features/reference-data/reference-data-add/reference-data-add.component.spec.ts
  src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/reference-data/reference-data-routing.module.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.html
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.ts
  src/app/features/reference-data/reference-data.module.ts
  src/app/forms/templates/reference-data/brakes.ts
  src/app/forms/templates/reference-data/country-of-registration.ts
  src/app/forms/templates/reference-data/hgv-make.ts
  src/app/forms/templates/reference-data/psv-make.ts
  src/app/forms/templates/reference-data/reasons-for-abandoning-TIR.ts
  src/app/forms/templates/reference-data/reasons-for-abandoning-TRL.ts
  src/app/forms/templates/reference-data/reasons-for-abandoning-hgv.ts
  src/app/forms/templates/reference-data/reasons-for-abandoning-psv.ts
  src/app/forms/templates/reference-data/specialist-reasons-for-abandoning.ts
  src/app/forms/templates/reference-data/trl-make.ts
  src/app/forms/templates/reference-data/tyres.ts
Labels: bug

#1012 refactor(cb2-0000): remove duplicate method
  src/app/services/batch-technical-record/batch-technical-record.service.spec.ts
  src/app/services/batch-technical-record/batch-technical-record.service.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: refactor

#1022 feat(cb2-7847): adds body type Other tanker
  src/app/models/body-type-enum.ts
Labels: enhancement

#1023 fix(cb2-8242): Adding reference data - template errors
  src/app/forms/templates/reference-data/brakes.ts
  src/app/forms/templates/reference-data/psv-make.ts
  src/app/forms/templates/reference-data/tyres.ts
Labels: bug

#1025 feat(cb2-8194): error handling for existing reference data resource keys
  src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
Labels: enhancement

#1029 fix(cb2-0000): minor content change
  src/app/features/tech-record/create/create-tech-record.component.html
Labels: bug
