Repository dvsa/cvs-app-vtm, pull requests merged in 2023-09, with the labels that each got.

#1129 feat(cb2-8777): Vehicle technical record errors
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Labels: enhancement

#1133 feat(cb2-8777): Create test record validation message
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Labels: enhancement

#1134 fix(cb2-8968): adds psv brakeCode fix to root of the techRecord
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
Labels: bug

#1135 fix(cb2-8806): updating hidden in vta on small trl removes number of axles
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.spec.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.spec.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/axles/axles.service.ts
  src/app/services/technical-record-http/technical-record-http.service.spec.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
Labels: bug

#1126 feat(cb2-8139): update options enum to use new labels
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#1136 fix(cb2-8666): add techRecord_ prefix and bump types
  package-lock.json
  package.json
  src/app/forms/custom-sections/weights/weights.component.ts
Labels: bug

#1127 feat(cb2-8230): reduce duplication of data entry for psvs
  src/app/forms/components/radio-group/radio-group.component.scss
  src/app/forms/components/radio-group/radio-group.component.ts
  src/app/forms/components/select/select.component.scss
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1137 feat(cb2-8230): reduce duplication of data entry for psvs
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1138 chore(cb2-8666): bump types package
  package-lock.json
  package.json
Labels: task

#1139 feat(cb2-8230): reduce duplication of data entry for psvs
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1140 feat(cb2-8230): reduce duplication of data entry for psvs
  src/app/forms/components/radio-group/radio-group.component.scss
  src/app/forms/components/select/select.component.scss
Labels: enhancement

#1142 fix(cb2-9038): moved clear section states action to correct location
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Labels: bug

#1143 chore(cb2-0000): update type definition
  package-lock.json
  package.json
Labels: task

#1145 chore(cb2-0000): update types and change default for techRecord_numberOfWheelsDriven
  package-lock.json
  package.json
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
Labels: task

#1141 feat(cb2-8705): type approval number validation
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
  src/app/forms/components/approval-type/approval-type-focus-next.directive.ts
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.scss
  src/app/forms/components/approval-type/approval-type.component.ts
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/custom-sections/approval-type/approval-type.component.html
  src/app/forms/custom-sections/approval-type/approval-type.component.scss
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/general/defect.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
  src/app/forms/templates/test-records/section-templates/seatbelt/seatbelt-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1149 fix(cb2-9083): correct vehicle class description
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#1148 fix(cb2-9080): psv record brake rendering issue
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#1151 feat(cb2-8709): Highlight testable fields
  src/app/forms/components/autocomplete/autocomplete.component.html
  src/app/forms/components/autocomplete/autocomplete.component.scss
  src/app/forms/components/autocomplete/autocomplete.component.ts
  src/app/forms/components/checkbox-group/checkbox-group.component.html
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/select/select.component.html
  src/app/forms/components/text-area/text-area.component.html
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/general/reason-for-creation.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/shared/components/tag/tag.component.ts
Labels: enhancement

#1153 feat(cb2-8709): Add missing hint for required fields
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: enhancement

#1154 feat(cb2-8557): Add back button to test cancel page
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.html
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts
Labels: enhancement

#1152 CB2-8705: Fix amend submission issue
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/custom-sections/approval-type/approval-type.component.html
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
Labels: bug

#1156 fix(cb2-8705): fix approval type anchor link and letters being null
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.ts
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/custom-sections/approval-type/approval-type.directive.ts
  src/app/forms/custom-sections/letters/letters.component.ts
Labels: bug

#1158 fix(CB2-8591): Correct vin custom validator message
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1155 feat(cb2-8710): improve the efficiency of performing a cherished transfer
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.scss
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#1159 fix(cb2-8709): Fix label rendering issues
  src/app/forms/components/checkbox-group/checkbox-group.component.html
  src/app/forms/components/number-input/number-input.component.html
Labels: bug

#1163 feat(cb2-9086): handle no defect taxonomy
  src/app/forms/components/defect-select/defect-select.component.html
Labels: enhancement

#1166 feat(cb2-9087): handle no test types
  src/app/features/test-records/components/test-type-select/test-type-select.component.html
Labels: enhancement

#1164 fix(cb2-8709): Add additional required tags and remove invalid ones
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
Labels: bug

#1169 fix(cb2-9119): allow space in conversion ref no
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
Labels: bug

#1170 fix(cb2-9118): multiple error messages while operation processes
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
Labels: bug

#1174 fix(CB2-8705): Allow approval type number to be cleared after form submission
  src/app/forms/components/approval-type/approval-type.component.ts
Labels: bug

#1175 fix(cb2-8710): improve the efficiency of performing a cherished transfer
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
Labels: bug

#1171 feat(cb2-7464): plate generation validation
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/date/date.component.html
  src/app/forms/custom-sections/plates/plates.component.html
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/custom-sections/weights/weights.component.html
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/models/plateRequiredFields.model.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tyres.template.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/trl/trl-dimensions.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/templates/trl/trl-tyres.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/shared/components/tag/tag.component.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: enhancement

#1177 fix(cb2 8225) Remove client-side unarchival checks
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/store/global-error/reducers/global-error-service.reducer.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#1181 fix(cb2-7464): plate validation
  src/app/forms/custom-sections/plates/plates.component.ts
Labels: bug

#1178 fix(cb2-8705): fix to observables & higher and lower values
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/templates/general/approval-type.template.ts
Labels: bug

#1179 chore(cb2-9166): bump type-def package
  package-lock.json
  package.json
  src/app/forms/custom-sections/plates/plates.component.spec.ts
Labels: task

#1183 fix(CB2-8705): Fix for the full pattern regex, partial pattern regex & observables
  src/app/forms/components/approval-type/approval-type.component.ts
  src/app/forms/custom-sections/plates/plates.component.ts
Labels: bug

#1184 fix(CB2-8714): Gross laden weight override
  src/app/forms/custom-sections/weights/weights.component.ts
Labels: bug

#1182 feat(cb2-7045): create from search
  src/app/features/search/multiple-search-results/multiple-search-results.component.html
  src/app/features/search/multiple-search-results/multiple-search-results.component.spec.ts
Labels: enhancement

#1186 fix(cb2-9195): fixes email validation for multiple-period domain addresses
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1187 feat(cb2-7122): solved unable view archived record bug
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
Labels: enhancement

#1190 fix(CB2-8705): allow special characters in the approval number
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.ts
Labels: bug

#1189 feat(cb2-9124): when returning to tech record maintain scroll position
  src/app/features/search/search.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: enhancement

#1196 fix(cb2-9199): fix the Overlapping CSS in Record type bug
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
Labels: bug

#1195 fix(cb2-9086): include breadcrumb to navigate to test creation screen
  src/app/core/components/breadcrumbs/breadcrumbs.component.html
  src/app/core/components/breadcrumbs/breadcrumbs.component.spec.ts
  src/app/core/components/breadcrumbs/breadcrumbs.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
Labels: bug

#1198 feat(cb2-9124): when returning to tech record maintain scroll position
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/letters/letters.component.ts
Labels: enhancement
