Repository dvsa/cvs-app-vtm, pull requests merged in 2023-02, with the labels that each got.

#824 fix(cb2-7439): filter body types by vehicle type
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/custom-sections/body/body.component.ts
Labels: bug

#831 feat(*): add create auto labelling and assignee action
  .github/workflows/pr-label-and-assign.yml
Labels: enhancement

#813 test(*): increase unit test coverage
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
  src/app/services/reference-data/reference-data.service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
  src/app/store/reference-data/selectors/reference-data.selectors.ts
Labels: coverage

#829 feat(cb2-7247): revert use of new input for further testing
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/switchable-input/switchable-input.component.html
Labels: refactor

#825 feat(cb2-5698): adjust isunique
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#830 refactor(cb2-7456): big tech records refactor
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.html
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.spec.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record.component.html
  src/app/features/tech-record/tech-record.component.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: bug, improvement, refactor

#832 feat(cb2-7273): Trigger Plate Generation
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.scss
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement

#823 feat(cb2-7397): add the small trailer vehicle type
  src/app/api/test-types/model/testType.ts
  src/app/api/test-types/model/testTypeCategory.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: enhancement

#835 fix(cb2-9999): correct body type code letter
  src/app/models/body-type-enum.ts
Labels: bug

#809 feat(cb2-7027): create light vehicle test group 3
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/specialist-required-hidden-section-lgv-car.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/group-3-light-vehicle-section.template.ts
Labels: enhancement

#837 fix(cb2-7489): get the vehicle type from the calculated tech record
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#838 feat(CB2-6750): View plates
  src/app/api/document-retrieval/api/document-retrieval.service.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/shared/components/view-plate/view-plate.component.html
  src/app/shared/components/view-plate/view-plate.component.scss
  src/app/shared/components/view-plate/view-plate.component.spec.ts
  src/app/shared/components/view-plate/view-plate.component.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#841 fix(cb2-7489): bug fix for changing vehicle type
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Labels: bug

#843 fix(cb2-7491): routing error when submitting a promote to current
  src/app/features/create/create.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.scss
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
Labels: bug, enhancement, refactor

#845 fix(cb2-7027): add the new test type and correct body type codes
  src/app/forms/models/testTypeId.enum.ts
  src/app/models/body-type-enum.ts
Labels: bug

#844 fix(cb2-7512): fix view tech record history
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
Labels: bug

#842 feat(cb2-7468): hide route breaking links from tech record
  src/app/features/search/search.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.scss
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/models/roles.enum.ts
  src/app/store/test-types/effects/test-types.effects.ts
Labels: enhancement, improvement, refactor

#840 feat(cb2-6427): implement parking brake checkboxes and revamp axle workflows
  src/app/app-routing.module.ts
  src/app/features/create/create.module.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/features/tech-record/create/create-tech-record.component.html
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/features/tech-record/create/create-tech-records-routing.module.ts
  src/app/features/tech-record/create/create-tech-records.module.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.spec.ts
  src/app/forms/components/checkbox/checkbox.component.html
  src/app/forms/components/checkbox/checkbox.component.spec.ts
  src/app/forms/components/checkbox/checkbox.component.ts
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.scss
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.ts
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.html
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.scss
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/psv/psv-brakes.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/services/axles/axles.service.spec.ts
  src/app/services/axles/axles.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: enhancement, improvement, refactor

#849 fix(cb2-9876): correct the ngswitch
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
Labels: bug

#846 feat(cb2-6178): cherished transfer checks
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
Labels: enhancement

#856 fix(cb2-7503)
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
Labels: bug

#857 fix(cb2-7522): fix the vrm and z number validation
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/utils/error-message-map.ts
Labels: bug, refactor

#858 fix(cb2-7537): Editing Tech Record and Vehicle Tech Record don't always match
  src/app/app-routing.module.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.spec.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/tech-record.component.ts
  src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.spec.ts
  src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.ts
Labels: bug, improvement

#860 fix(cb2-7565): display skeleton TRLs and HGVs
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/services/axles/axles.service.ts
Labels: bug

#859 feat(cb2-7355): generate plates
  src/app/api/document-retrieval/api/document-retrieval.service.ts
  src/app/api/vehicle/model/letters.ts
  src/app/api/vehicle/model/techRecord.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.scss
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.scss
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/letters/letters.component.scss
  src/app/forms/custom-sections/letters/letters.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.ts
  src/app/forms/custom-sections/plates/plates.component.html
  src/app/forms/custom-sections/plates/plates.component.scss
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/general/letter-types.ts
  src/app/forms/templates/general/letters.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement

#864 fix(cb2-7587): refresh the tech record after generating new plates
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug, improvement, refactor

#865 fix(cb2-7589): potential fix for broken trailers
  src/app/api/vehicle/model/letters.ts
  src/app/api/vehicle/model/techRecord.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/forms/custom-sections/letters/letters.component.ts
  src/app/forms/templates/general/letters.template.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: bug

#866 fix(cb2-7600): Changing a Provisional record to Current doesn't update Tech Record properly
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#869 feat(cb2-7541): Create a HGV Type Approved Tractor Unit DBA
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
Labels: enhancement

#870 feat(cb2-7479): create a directive to handle document downloads
  src/app/api/document-retrieval/api/document-retrieval.service.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/letters/letters.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.ts
  src/app/forms/custom-sections/plates/plates.component.html
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/templates/psv/psv-brakes.template.ts
  src/app/services/documents/documents.service.spec.ts
  src/app/services/documents/documents.service.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/components/test-certificate/test-certificate.component.html
  src/app/shared/components/test-certificate/test-certificate.component.ts
  src/app/shared/directives/retrieve-document/retrieve-document.directive.spec.ts
  src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
  src/app/shared/shared.module.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement, improvement

#873 fix(cb2-7614): remove validation before submitting
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#875 fix(cb2-7626): fix letters breaking templates
  src/app/forms/custom-sections/letters/letters.component.html
Labels: bug

#874 feat(cb2-7603): amend vin
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#868 feat(CB2-7471): trigger trailer into service generation
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/letters/letters.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.ts
  src/app/forms/custom-sections/plates/plates.component.html
  src/app/forms/templates/general/letter-types.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/documents/documents.service.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement

#878 fix(cb2-7610): initialise parkingBrakeMrk to false
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#882 feat(cb2-7603): removed references to old vin and created test
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#884 fix(cb2-7632): added check for if trailer has letter
  src/app/forms/custom-sections/letters/letters.component.html
Labels: bug

#876 fix(cb2-7615): manual tyre search
  src/app/forms/custom-sections/tyres/tyres.component.ts
Labels: bug

#887 fix(cb2-7638): fix routing when provisional
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
Labels: bug

#889 feat(cb2-7579): remove small trailer VRM
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/letters/letters.component.ts
Labels: enhancement

#891 feat(cb2-7603): Amend VIN
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
Labels: enhancement

#892 fix(cb2-7640): default eec weight to null on hgv and trl
  src/app/forms/validators/custom-async-validators.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#890 fix(cb2-7641): add vehicle configuration to motorcycle required template
  src/app/forms/templates/test-records/section-templates/required/specialist-required-hidden-section-motorcycle.template.ts
Labels: bug

#897 CB2-7668
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.html
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
Labels: bug

#899 feat(cb2-5697): amend vin
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.html
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#902 fix(cb2-7683): fix email not defaulting to user email
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#905 fix(cb2-7683): fix email issue
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/services/technical-record/technical-record.service.ts
Labels: bug
