Repository dvsa/cvs-app-vtm, pull requests merged in 2023-10, with the labels that each got.

#1192 feat(cb2-8121): lint for guards and interceptor folders
  .eslintignore
  src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.spec.ts
  src/app/guards/cancel-edit-tech/cancel-edit-tech.guard.ts
  src/app/guards/cancel-edit-test/cancel-edit-test.guard.spec.ts
  src/app/guards/cancel-edit-test/cancel-edit-test.guard.ts
  src/app/guards/no-edit/no-edit.guard.spec.ts
  src/app/guards/no-edit/no-edit.guard.ts
  src/app/guards/no-query-params/no-query-params.guard.spec.ts
  src/app/guards/no-query-params/no-query-params.guard.ts
  src/app/guards/role-guard/roles.guard.spec.ts
  src/app/guards/role-guard/roles.guard.ts
  src/app/interceptors/delayed-retry/delayed-retry.interceptor.spec.ts
  src/app/interceptors/delayed-retry/delayed-retry.interceptor.ts
  src/app/interceptors/delayed-retry/delayed-retry.module.ts
  src/app/interceptors/error-handling/error-handling.interceptor.spec.ts
  src/app/interceptors/error-handling/error-handling.interceptor.ts
  src/app/interceptors/error-handling/error-handling.module.ts
  src/app/interceptors/interceptor.module.ts
Labels: bug, enhancement

#1200 feat(cb2-8121): eslint errors fixed in resolvers
  .eslintignore
  src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
  src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.spec.ts
  src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.ts
  src/app/resolvers/test-result/test-result.resolver.spec.ts
  src/app/resolvers/test-result/test-result.resolver.ts
  src/app/resolvers/test-stations/test-stations.resolver.spec.ts
  src/app/resolvers/test-stations/test-stations.resolver.ts
  src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.spec.ts
  src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.ts
  src/app/resolvers/title/title.resolver.spec.ts
  src/app/resolvers/title/title.resolver.ts
Labels: enhancement

#1201 feat(cb2-8121): replace tslint with eslint for all cvs typescript repos
  .eslintignore
  src/app/forms/custom-sections/defect/defect.component.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/body-type-enum.ts
  src/app/models/coupling-type-enum.ts
  src/app/models/defects/deficiency-category.enum.ts
  src/app/models/defects/location.model.ts
  src/app/models/reference-data.model.ts
  src/app/models/roles.enum.ts
  src/app/models/tech-record/tech-record-actions.enum.ts
  src/app/models/test-results/defectAdditionalInformation.ts
  src/app/models/test-results/defectAdditionalInformationLocation.ts
  src/app/models/test-results/test-result-defect.model.ts
  src/app/models/test-results/test-result-defects.model.ts
  src/app/models/test-results/test-result-status.enum.ts
  src/app/models/test-results/test-result-view.enum.ts
  src/app/models/test-results/testCodes.enum.ts
  src/app/models/test-results/typeOfTest.enum.ts
  src/app/models/test-stations/test-station-type.enum.ts
  src/app/models/test-stations/test-station.model.ts
  src/app/models/test-types/emissions.enum.ts
  src/app/models/test-types/eu-vehicle-category.enum.ts
  src/app/models/test-types/odometer-unit.enum.ts
  src/app/models/test-types/test-type.model.ts
  src/app/models/vehicle-class.model.ts
  src/app/models/vehicle-configuration.enum.ts
  src/app/models/vehicle-size.enum.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
  src/app/store/test-types/selectors/test-types.selectors.ts
  src/mocks/mock-defects.ts
  src/mocks/reference-data/mock-countries-of-registration.reference-data.ts
Labels: enhancement

#1193 feat(CB2-9114): Amend vehicle VIN validation
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.html
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
Labels: enhancement

#1204 fix(cb2-9200): fix the Axle Weights not incrementing
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/weights/weights.component.ts
Labels: bug

#1205 feat(cb2-8121): eslint errors fixed in services
  .eslintignore
  src/app/features/search/multiple-search-results/multiple-search-results.component.ts
  src/app/features/search/search.component.spec.ts
  src/app/features/search/search.component.ts
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/models/search-types-enum.ts
  src/app/services/axles/axles.service.spec.ts
  src/app/services/axles/axles.service.ts
  src/app/services/batch-technical-record/batch-technical-record.service.spec.ts
  src/app/services/batch-technical-record/batch-technical-record.service.ts
  src/app/services/defects/defects.service.spec.ts
  src/app/services/documents/documents.service.ts
  src/app/services/loading/loading.service.spec.ts
  src/app/services/loading/loading.service.ts
  src/app/services/reference-data/reference-data.service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/services/result-of-test/result-of-test.service.spec.ts
  src/app/services/result-of-test/result-of-test.service.ts
  src/app/services/router/router.service.spec.ts
  src/app/services/router/router.service.ts
  src/app/services/technical-record-http/technical-record-http.service.spec.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/services/test-records/test-records.service.spec.ts
  src/app/services/test-records/test-records.service.ts
  src/app/services/test-stations/test-stations.service.spec.ts
  src/app/services/test-stations/test-stations.service.ts
  src/app/services/test-types/test-types.service.spec.ts
  src/app/services/test-types/test-types.service.ts
  src/app/services/user-service/user-service.spec.ts
  src/app/services/user-service/user-service.ts
  src/app/store/tech-record-search/actions/tech-record-search.actions.ts
  src/app/store/tech-record-search/effects/tech-record-search.effect.spec.ts
  src/app/store/tech-record-search/effects/tech-record-search.effect.ts
Labels: enhancement

#1209 feat(CB2-9190): Implementation of new update VIN endpoint
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement

#1206 feat(cb2-8121): replace tslint with eslint for all cvs typescript repos
  .eslintignore
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/resolvers/test-result/test-result.resolver.spec.ts
  src/app/shared/components/accordion-control/accordion-control.component.spec.ts
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/shared/components/accordion/accordion.component.spec.ts
  src/app/shared/components/accordion/accordion.component.ts
  src/app/shared/components/banner/banner.component.spec.ts
  src/app/shared/components/banner/banner.component.ts
  src/app/shared/components/base-dialog/base-dialog.component.spec.ts
  src/app/shared/components/base-dialog/base-dialog.component.ts
  src/app/shared/components/button-group/button-group.component.spec.ts
  src/app/shared/components/button-group/button-group.component.ts
  src/app/shared/components/button/button.component.spec.ts
  src/app/shared/components/button/button.component.ts
  src/app/shared/components/icon/icon.component.spec.ts
  src/app/shared/components/icon/icon.component.ts
  src/app/shared/components/input-spinner/input-spinner.component.spec.ts
  src/app/shared/components/input-spinner/input-spinner.component.ts
  src/app/shared/components/number-plate/number-plate.component.spec.ts
  src/app/shared/components/number-plate/number-plate.component.ts
  src/app/shared/components/pagination/pagination.component.spec.ts
  src/app/shared/components/pagination/pagination.component.ts
  src/app/shared/components/router-outlet/router-outlet.component.spec.ts
  src/app/shared/components/router-outlet/router-outlet.component.ts
  src/app/shared/components/tag/tag.component.spec.ts
  src/app/shared/components/tag/tag.component.ts
  src/app/shared/components/test-certificate/test-certificate.component.spec.ts
  src/app/shared/components/test-certificate/test-certificate.component.ts
  src/app/shared/custom-module/fixNgZoneError.ts
  src/app/shared/directives/prevent-double-click/prevent-double-click.directive.spec.ts
  src/app/shared/directives/prevent-double-click/prevent-double-click.directive.ts
  src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
  src/app/shared/pipes/default-null-or-empty/default-null-or-empty.pipe.spec.ts
  src/app/shared/pipes/default-null-or-empty/default-null-or-empty.pipe.ts
  src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.spec.ts
  src/app/shared/pipes/digit-group-separator/digit-group-separator.pipe.ts
  src/app/shared/pipes/format-vehicle-type/format-vehicle-type.pipe.spec.ts
  src/app/shared/pipes/format-vehicle-type/format-vehicle-type.pipe.ts
  src/app/shared/pipes/get-control-label/get-control-label.pipe.spec.ts
  src/app/shared/pipes/get-control-label/get-control-label.pipe.ts
  src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.spec.ts
  src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
  src/app/shared/pipes/test-type-name/test-type-name.pipe.spec.ts
  src/app/shared/pipes/test-type-name/test-type-name.pipe.ts
  src/app/shared/pipes/truncate/truncate.pipe.ts
  src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.spec.ts
  src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#1211 fix(cb2-9046): current tech record VIN warnings
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#1213 fix(cb2-9269): iva test types missing for lgv and psv provisional tech records
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Labels: bug

#1220 fix(cb2-7505): free input box on small series
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.ts
Labels: bug

#1221 fix(cb2-8714): repair override function and ceil value for weights
  src/app/forms/custom-sections/weights/weights.component.ts
Labels: bug

#1215 fix(CB2-9039): provisional url not required
  package-lock.json
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
Labels: bug

#1218 feat(cb2-8971): add summary screen
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.scss
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/custom-sections/modified-weights/modified-weights.component.html
  src/app/forms/custom-sections/modified-weights/modified-weights.component.scss
  src/app/forms/custom-sections/modified-weights/modified-weights.component.spec.ts
  src/app/forms/custom-sections/modified-weights/modified-weights.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/tech-records/vehicle-summary.template.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/shared.module.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: enhancement

#1224 feat(cb2-8971): summary screen for tech record amendments
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/forms/custom-sections/modified-weights/modified-weights.component.html
Labels: enhancement

#1225 feat(cb2-8121): remove all unused imports to reduce linting warnings
  .prettierrc
  src/app/features/reference-data/reference-data-add/reference-data-add.component.spec.ts
  src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.ts
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive.component.spec.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.spec.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
  src/app/features/test-records/amend/views/test-amend-reason/test-amend-reason.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.spec.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.ts
  src/app/forms/validators/custom-validators.ts
  src/app/guards/no-query-params/no-query-params.guard.spec.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
Labels: enhancement

#1222 feat(cb2-9639): replace deprecated Resolver class
  src/app/app-routing.module.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.spec.ts
  src/app/resolvers/contingency-test/contingency-test.resolver.ts
  src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.spec.ts
  src/app/resolvers/defects-taxonomy/defects-taxonomy.resolver.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.ts
  src/app/resolvers/test-result/test-result.resolver.spec.ts
  src/app/resolvers/test-result/test-result.resolver.ts
  src/app/resolvers/test-stations/test-stations.resolver.spec.ts
  src/app/resolvers/test-stations/test-stations.resolver.ts
  src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.spec.ts
  src/app/resolvers/test-type-taxonomy/test-type-taxonomy.resolver.ts
  src/app/resolvers/title/title.resolver.spec.ts
  src/app/resolvers/title/title.resolver.ts
Labels: enhancement

#1228 feat(cb2-8971): rech record changes summary
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
Labels: enhancement

#1230 fix(cb2-9679): add font-family to autocomplete options
  src/app/forms/components/autocomplete/autocomplete.component.scss
Labels: bug

#1233 feat(cb2-9680): edit emissions label
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
Labels: enhancement

#1235 feat(cb2-9601): update vehicle configuration options
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/body-type-enum.ts
  src/app/models/vehicle-configuration.enum.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement

#1239 feat(cb2-9601): update vehicle configuration options
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/models/body-type-enum.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
Labels: enhancement

#1238 feat(cb2-9183): update vehicle class
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/forms/custom-sections/letters/letters.component.spec.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/mocks/hgv-record.mock.ts
  src/mocks/psv-record.mock.ts
  src/mocks/trl-record.mock.ts
Labels: enhancement
