Repository dvsa/cvs-app-vtm, pull requests merged in 2023-04, with the labels that each got.

#983 fix(cb2-7952): vehicle size not allowed in test
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/required/contingency-required-hidden-section-hgv-trl.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-lgv.template.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#984 fix(cb2-7972): add toggle to content children
  src/app/shared/components/accordion-control/accordion-control.component.ts
Labels: bug

#982 fix(cb2-7966): changing vehicle type
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#985 fix(cb2-7976, 7979): fix generate plate subscribe event
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.html
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
Labels: bug

#986 fix(cb2-7997): fixes the axle tyre details getting values from existing tyre fields
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#988 feat(cb2-7759): navigate to the summary page after creating a tech record
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement, improvement

#990 feat(cb2-7886): add user survey to VTM
  src/app/app.component.html
  src/app/core/components/phase-banner/phase-banner.component.html
  src/app/core/components/phase-banner/phase-banner.component.scss
  src/app/core/components/phase-banner/phase-banner.component.spec.ts
  src/app/core/components/phase-banner/phase-banner.component.ts
  src/app/core/core.module.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#991 feat(cb2-7887): implement google analytics
  src/app/app.component.ts
  src/app/services/google-analytics/google-analytics.service.spec.ts
  src/app/services/google-analytics/google-analytics.service.ts
  src/index.html
Labels: enhancement

#987 test(*): add cypress for local e2e testing
  .gitignore
  .prettierignore
  cypress.config.ts
  cypress/e2e/techRecord/HGV/hgv.cy.ts
  cypress/e2e/techRecord/LGV/lgv.cy.ts
  cypress/e2e/techRecord/PSV/psv.cy.ts
  cypress/e2e/techRecord/TRL/trl.cy.ts
  cypress/e2e/testResults/HGV/tests.cy.ts
  cypress/e2e/testResults/LGV/DBA.cy.ts
  cypress/e2e/testResults/TRL/tests.cy.ts
  cypress/fixtures/433.json
  cypress/fixtures/hgv-testable.json
  cypress/fixtures/lgv.json
  cypress/fixtures/psv.json
  cypress/fixtures/trl-testable.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
  cypress/tsconfig.json
  makefile
  package-lock.json
  package.json
  setenv.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/test-records/amend/components/test-amendment-history/test-amendment-history.component.html
  src/app/services/user-service/user-service.ts
Labels: coverage, improvement

#992 fix(cb2-8052):Unable to create vehicles with classes: PSV of Unknown size or Not Know
  src/app/api/test-results/model/completeTestResultsVehicleClass.ts
  src/app/api/vehicle/model/techRecordVehicleClass.ts
  src/app/models/vehicle-class.model.ts
Labels: bug

#994 feature CB2-7951: Unable to identify a small trailer as an O2 EU category
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Labels: enhancement

#993 test(cb2-7951): update cypress data to match new trailer rules
  cypress/e2e/testResults/TRL/tests.cy.ts
Labels: bug, coverage

#996 fix(cb2-7965): improve directives and add alphanumeric validators
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-details/batch-trl-details.component.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/directives/app-no-space.directive.spec.ts
  src/app/forms/directives/app-no-space.directive.ts
  src/app/forms/directives/app-trim-whitespace.directive.spec.ts
  src/app/forms/directives/app-trim-whitespace.directive.ts
Labels: bug

#998 fix(cb2-8107): fix tyre search routing for batch create
  src/app/features/tech-record/create-batch-trl/create-batch-trl-routing.module.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
Labels: bug

#1003 chore(cb2-0000): update ts config to handle cypress and jest types
  cypress/tsconfig.json
  tsconfig.json
Labels: task

#1007 feat(cb2-7927): Euro 5
  src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/models/test-types/emissions.enum.ts
Labels: enhancement

#1009 fix(cb2-8109): allow failed tests to send without dates
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
Labels: bug

#1010 feat(cb2-7899): axle load from index
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.html
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/models/reference-data.model.ts
  src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.spec.ts
  src/app/shared/pipes/tyre-axle-load/tyre-axle-load.pipe.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#1011 fix(cb2-0000): fix build failing between merges
  src/app/features/reference-data/reference-data-routing.module.ts
Labels: bug

#1008 chore(cb2-6935): update all packages
  .github/workflows/pr-checks.yml
  .nvmrc
  README.md
  jest.config.js
  package-lock.json
  package.json
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.html
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/create-batch-trl/components/batch-trl-template/batch-trl-template.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/test-records/amend/views/amended-test-record/amended-test-record.component.html
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/forms/components/select/select.component.spec.ts
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/custom-sections/defects/defects.component.html
  src/app/forms/custom-sections/letters/letters.component.html
  src/app/forms/custom-sections/plates/plates.component.html
  src/app/forms/validators/custom-async-validators.spec.ts
  src/app/guards/no-query-params/no-query-params.guard.spec.ts
  src/app/shared/custom-module/fixNgZoneError.ts
  src/app/store/defects/selectors/defects.selectors.spec.ts
  src/app/store/router/selectors/router.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/test-records/selectors/test-records.selectors.spec.ts
  src/app/store/test-stations/selectors/test-stations.selectors.spec.ts
Labels: task

#1013 feat(cb2-7927): restore euro VI
  src/app/models/test-types/emissions.enum.ts
Labels: enhancement
