Repository dvsa/cvs-app-vtm, pull requests merged in 2023-11, with the labels that each got.

#1241 feat(cb2-9595): Update EU Vehicle Category options
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/group-3-light-vehicle-section.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/models/test-results/test-result.model.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/mocks/mock-test-result.ts
  src/mocks/trl-record.mock.ts
Labels: enhancement

#1243 feat(cb2-9601): update vehicle configuration options
  package-lock.json
  package.json
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/models/body-type-enum.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/mocks/hgv-record.mock.ts
  src/mocks/psv-record.mock.ts
  src/mocks/trl-record.mock.ts
Labels: enhancement

#1245 feat(cb2-9669): create VTM feature toggle tools
  setenv.ts
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/directives/feature-toggle.directive.spec.ts
  src/app/directives/feature-toggle.directive.ts
  src/app/features/feature-toggle/feature-toggle-routing.module.ts
  src/app/features/feature-toggle/feature-toggle.module.ts
  src/app/features/feature-toggle/feature-toggle/feature-toggle.component.html
  src/app/features/feature-toggle/feature-toggle/feature-toggle.component.ts
  src/app/features/home/home.component.html
  src/app/guards/feature-toggle-guard/feature-toggle.guard.spec.ts
  src/app/guards/feature-toggle-guard/feature-toggle.guard.ts
  src/app/services/feature-toggle-service/featuer-toggle-service.spec.ts
  src/app/services/feature-toggle-service/feature-toggle-service.ts
  src/app/shared/shared.module.ts
  src/assets/featureToggle.json
  src/assets/featureToggle.prod.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#1246 feat(cb2-9601): update vehicle configuration
  .eslintignore
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/resolvers/tech-record-view/tech-record-view.resolver.spec.ts
Labels: enhancement

#1247 feat(cb2-9603): update approval type dropdown
  package-lock.json
  package.json
  src/app/forms/components/select/select.component.html
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
Labels: enhancement

#1231 feat(cb2-8121): fix linting issue
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/forms/components/defect-select/defect-select.component.ts
  src/app/forms/custom-sections/defect/defect.component.spec.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/guards/no-edit/no-edit.guard.spec.ts
  src/app/services/reference-data/reference-data.service.spec.ts
Labels: enhancement

#1251 chore(cb2-9596): bumped types package
  package-lock.json
  package.json
Labels: task

#1252 feat(cb2-9650): Small series approval type
  angular.json
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.component.ts
  src/app/forms/components/approval-type/approval-type.component.html
  src/app/forms/components/approval-type/approval-type.component.ts
  src/app/forms/custom-sections/approval-type/approval-type.component.html
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/resolvers/tech-record-clean/tech-record-clean.resolver.spec.ts
  src/app/resolvers/tech-record-clean/tech-record-clean.resolver.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.ts
  src/mocks/hgv-record.mock.ts
  src/mocks/psv-record.mock.ts
  src/mocks/trl-record.mock.ts
Labels: enhancement

#1259 fix(cb2-0000): Small fix for hgvs
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/models/body-type-enum.ts
Labels: bug

#1236 feat(cb2-8121): remove need to disable ESLint error
  .eslintrc
  src/app/core/components/breadcrumbs/breadcrumbs.component.ts
  src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
  src/app/features/reference-data/reference-data-amend/reference-data-amend.component.ts
  src/app/features/reference-data/reference-data-delete/reference-data-delete.component.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.ts
  src/app/features/search/search.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-amend-reason/tech-record-amend-reason.component.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/tech-record-unarchive/tech-record-unarchive-component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
  src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts
  src/app/features/test-records/amend/views/test-amend-reason/test-amend-reason.component.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/amend/views/test-type-select-wrapper/test-type-select-wrapper.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.ts
  src/app/forms/components/defect-select/defect-select.component.ts
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.spec.ts
  src/app/forms/custom-sections/defect/defect.component.ts
  src/app/forms/custom-sections/letters/letters.component.ts
  src/app/forms/custom-sections/modified-weights/modified-weights.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/interceptors/error-handling/error-handling.interceptor.ts
  src/app/services/technical-record-http/technical-record-http.service.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.spec.ts
  src/app/store/test-stations/effects/test-stations.effects.spec.ts
Labels: enhancement

#1250 feat(cb2-8121): fix linting warnings
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.ts
  src/app/forms/components/autocomplete/autocomplete.component.ts
  src/app/forms/components/base-control/base-control.component.spec.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/services/dynamic-form.service.spec.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/reference-data.model.ts
  src/app/resolvers/tech-record-validate/tech-record-validate.resolver.spec.ts
  src/app/services/feature-toggle-service/featuer-toggle-service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
  src/app/services/test-records/test-records.service.spec.ts
  src/app/services/test-records/test-records.service.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
Labels: enhancement

#1261 fix(cb2-9870): repair check on hidden in VTA call
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#1257 feat(cb2-9728): add applicant details to adr section on a technical record
  angular.json
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/forms/components/autocomplete/autocomplete.component.html
  src/app/forms/components/checkbox-group/checkbox-group.component.html
  src/app/forms/components/date/date.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
  src/app/forms/components/radio-group/radio-group.component.html
  src/app/forms/components/select/select.component.html
  src/app/forms/components/suggestive-input/suggestive-input.component.html
  src/app/forms/components/text-area/text-area.component.html
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/custom-sections/adr/adr.component.html
  src/app/forms/custom-sections/adr/adr.component.scss
  src/app/forms/custom-sections/adr/adr.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.ts
  src/app/forms/directives/nesting-level/nesting-level.directive.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/store/technical-records/actions/technical-record-service.actions.spec.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/mocks/lgv-record.mock.ts
Labels: enhancement

#1256 feat(cb2-9598): validation for dates
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-auth-into-service.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/utils/error-message-map.spec.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1262 feat(cb2-9728): add error when attempting to generate plates
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/models/plateRequiredFields.model.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#1269 feat(cb2-9728): add applicant/operator details to adr section on a technical record
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: enhancement

#1270 feat(feature/cb2-9883): euro 3 text changed NOT THE VALUE
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/models/test-types/emissions.enum.ts
Labels: enhancement

#1272 feat(cb2-9056): filter first test / first test retest
  src/app/features/test-records/amend/views/test-type-select-wrapper/test-type-select-wrapper.component.spec.ts
  src/app/features/test-records/components/test-type-select/test-type-select.component.spec.ts
  src/app/features/test-records/components/test-type-select/test-type-select.component.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/test-types/selectors/test-types.selectors.spec.ts
  src/app/store/test-types/selectors/test-types.selectors.ts
Labels: enhancement

#1267 feat(cb2-8121): more fixes for eslint warnings
  src/app/accessible-autocomplete.d.ts
  src/app/features/home/home.component.spec.ts
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.spec.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.spec.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/forms/components/autocomplete/autocomplete.component.spec.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/number-input/number-input.component.spec.ts
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/models/condition.model.ts
  src/app/services/reference-data/reference-data.service.ts
Labels: enhancement

#1264 feat(cb2-9808): add sentry to VTM
  .github/workflows/pr-checks.yml
  .gitignore
  angular.json
  jest.config.js
  package-lock.json
  package.json
  setenv.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
Labels: enhancement

#1276 feat(cb2-7464): remove date of first registration as required field for trailer plate generation
  src/app/forms/models/plateRequiredFields.model.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: enhancement

#1278 fix(cb2-9056): hide all of retest for prov when current record exists
  src/app/store/test-types/selectors/test-types.selectors.ts
Labels: bug

#1260 fix(cb2-9039): navigate to current record
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/app/store/test-records/effects/test-records.effects.ts
Labels: bug

#1279 feat(cb2-9123): tyre and weight validation for hgv/trl/psv
  src/app/features/tech-record/create/create-tech-records-routing.module.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/forms/components/field-warning-message/field-warning-message.component.html
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/tyres/tyres.component.scss
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/resolvers/tech-record-data/tech-record-data.resolver.spec.ts
  src/app/resolvers/tech-record-data/tech-record-data.resolver.ts
Labels: enhancement

#1281 fix(cb2-9944): remove extra *
  src/app/forms/components/approval-type/approval-type.component.html
Labels: bug

#1283 fix(cb2-7464): approval type and number is optional for plates
  src/app/forms/models/plateRequiredFields.model.ts
  src/app/forms/templates/general/approval-type.template.ts
Labels: bug

#1288 fix(cb2-9937): review screen is broken
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#1290 fix(cb2-7464): add the tyre validation
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/models/plateRequiredFields.model.ts
Labels: bug
