Repository dvsa/cvs-app-vtm, pull requests merged in 2023-03, with the labels that each got.

#906 test(cb2-7684): fix broken unit tests and increase coverage
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-amend-reason/tech-record-amend-reason.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/create/create-tech-record.component.html
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/components/test-certificate/test-certificate.component.spec.ts
Labels: coverage

#910 fix(cb2-7666): Cannot amend Tech Record with frontVehicleTo5thWheelCouplingMax or Min
  src/app/api/vehicle/model/techRecord.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.html
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/mocks/hgv-record.mock.ts
Labels: bug

#911 fix(cb2-6641): do not display the audit section when editing tech records
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#912 fix(cb2-6641): make the no of axles editable and required on small vehicles
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Labels: bug, enhancement

#913 fix(cb2-7716): fix missing fields on light vehicle tests
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
Labels: bug

#919 fix(cb2-7731): accept only number inputs for no of wheels driven
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
Labels: bug

#918 fix(cb2-7729): handle array when merging tech record changes
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/components/checkbox-group/checkbox-group.component.html
  src/app/forms/components/checkbox-group/checkbox-group.component.ts
Labels: bug

#920 fix(cb2-7726): remove defects sections from light vehicles
  .gitignore
  package.json
  setenv.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
Labels: bug

#922 fix(cb2-6960): add test station details to review test screen
  src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts
Labels: bug

#921 feat(cb2-7653): add in from date to payload
  src/app/store/test-records/effects/test-records.effects.ts
Labels: enhancement

#923 fix(cb2-7726): no defects for motorcycle and lgv
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
Labels: bug

#924 fix(cb2-7742): add z number check to number plate
  src/app/shared/components/number-plate/number-plate.component.spec.ts
  src/app/shared/components/number-plate/number-plate.component.ts
Labels: bug

#915 feat(cb2-7532): create dba light vehicular tests
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section-group5-lgv.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group5-LGV.ts
Labels: enhancement

#927 fix(cb2-7118): make certain defect notes optional
  src/app/forms/validators/defects/defect.validators.ts
Labels: bug

#931 fix(cb2-7727): correct errors on the small trailers template
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Labels: bug

#914 feat(cb2-7061): enable changing vehicle type to light vehicles
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.html
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
Labels: enhancement

#932 fix(cb2-7727): allow creating small trailers
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
Labels: bug

#930 feat(cb2-7533): Amend a Light Vehicle DBA
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group5-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
Labels: enhancement

#934 fix(cb2-7533): template change to match validations
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
Labels: bug

#935 feat(cb2-7057): add the t numbers text to record creation
  src/app/features/tech-record/create/create-tech-record.component.html
  src/app/features/tech-record/create/create-tech-record.component.ts
Labels: enhancement

#936 feat(cb2-7532): create DBA test
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
Labels: enhancement

#937 feat(cb2-7532): create dba
  src/app/forms/templates/test-records/create-master.template.ts
Labels: enhancement

#938 feat(cb2-7533): create and amend DBA
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-motorcycle-amend.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-hidden-group4-motorcycle.template.ts
  src/app/forms/templates/test-records/section-templates/required/desk-based-required-section-group4-amend.template.ts
Labels: enhancement

#933 fix(cb2-7774, cb2-7775): vin and vrms uppercase, added no whitespace directive
  src/app/features/search/search.component.html
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/forms/directives/app-no-space.directive.spec.ts
  src/app/forms/directives/app-no-space.directive.ts
  src/app/forms/directives/app-to-uppercase.directive.spec.ts
  src/app/forms/directives/app-to-uppercase.directive.ts
  src/app/forms/directives/app-trim-whitespace.directive.spec.ts
  src/app/forms/directives/app-trim-whitespace.directive.ts
  src/app/forms/dynamic-forms.module.ts
Labels: bug

#939 fix(CB2-7775): add directives to fields
  src/app/features/search/search.component.html
  src/app/features/tech-record/create/create-tech-record.component.html
  src/app/forms/directives/app-to-uppercase.directive.spec.ts
  src/app/forms/directives/app-to-uppercase.directive.ts
Labels: bug

#929 feat(cb2-7162): amend VIN where a duplicate VIN exists
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.html
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.spec.ts
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/custom-defects/custom-defects.component.spec.ts
  src/app/forms/custom-sections/defect/defect.component.spec.ts
  src/app/forms/custom-sections/defects/defects.component.spec.ts
  src/app/forms/custom-sections/dimensions/dimensions.component.spec.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.spec.ts
  src/app/forms/custom-sections/trl-brakes/trl-brakes.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/weights/weights.component.spec.ts
  src/app/forms/services/dynamic-form.service.spec.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/services/dynamic-form.types.spec.ts
  src/app/forms/utils/error-message-map.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/components/icon/icon.component.html
  src/app/shared/components/input-spinner/input-spinner.component.html
  src/app/shared/components/input-spinner/input-spinner.component.scss
  src/app/shared/components/input-spinner/input-spinner.component.spec.ts
  src/app/shared/components/input-spinner/input-spinner.component.ts
  src/app/shared/shared.module.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
Labels: enhancement

#940 feat(cb2-7795): break down bodymake into hgvmake and trlmake
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
  src/app/models/reference-data.model.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/reducers/reference-data.reducer.ts
  src/app/store/reference-data/selectors/reference-data.selectors.spec.ts
Labels: enhancement

#942 fix(cb2-7162): amend vin validation message
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/forms/utils/error-message-map.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#943 feat(cb2-7795): hide null body models and extend the width of body fields
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/forms/custom-sections/body/body.component.html
Labels: enhancement

#948 fix(cb2-2001): enable editing test number for adr tests
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
Labels: bug

#949 fix(cb2-7021): fix on tech record create summary
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
Labels: bug

#950 fix(cb2-7833): preserve value type of the select element
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.spec.ts
Labels: bug

#952 fix(cb2-7829): navigate to tech record after updating test result
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
Labels: bug

#954 feat(cb2-7829): enable changing certificate number
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/shared/components/test-certificate/test-certificate.component.html
  src/app/shared/components/test-certificate/test-certificate.component.scss
  src/app/shared/components/test-certificate/test-certificate.component.ts
Labels: bug, enhancement

#951 fix(cb2 7812): adds TestCode to the test result header
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-lgv-template.ts
Labels: bug

#955 feat(cb2-7842): Cannot Amend a Cherished Transfer
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#958 feat(cb2-7842): update logic and add tests
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#944 feat(cb2-7652): implement the test cancellation workflow
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/amend/amend-test-records.module.ts
  src/app/features/test-records/amend/components/test-amendment-history/test-amendment-history.component.html
  src/app/features/test-records/amend/views/amended-test-record/amended-test-record.component.spec.ts
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.html
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.spec.ts
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.scss
  src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/components/result-of-test/result-of-test.component.html
  src/app/features/test-records/components/result-of-test/result-of-test.component.spec.ts
  src/app/features/test-records/components/result-of-test/result-of-test.component.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/features/test-records/test-records.module.ts
  src/app/models/test-results/test-result-status.enum.ts
  src/app/models/test-results/test-result.model.ts
  src/app/services/test-records/test-records.service.ts
  src/app/shared/components/tag/tag.component.ts
  src/app/store/test-records/actions/test-records.actions.ts
  src/app/store/test-records/effects/test-records.effects.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
  src/mocks/mock-test-result.ts
Labels: enhancement

#961 fix(cb2-7842): change update vrm behaviour
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#963 fix(cb2-7896): previous batch information is retained
  src/app/features/tech-record/create-batch-trl/components/batch-trl-results/batch-trl-results.component.ts
Labels: bug

#964 fix(cb2-7532): updates the DBA templates for group 4 and 5
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section-group5-lgv.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-lgv-template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group5-LGV.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group4-lgv.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
Labels: bug

#966 feat(cb2-7891): repair axle ordering
  src/app/services/axles/axles.service.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: enhancement

#967 fix(cb2-7839): added custom id tags for dynamic-form-field and select…
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/select/select.component.html
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/custom-sections/body/body.component.html
Labels: bug

#969 fix(cb2-7861): change value to display the email
  src/app/forms/validators/custom-async-validators.ts
Labels: bug

#968 fix(CB2-7845): added ids to create batch trailer page elements
  src/app/features/tech-record/create-batch-trl/components/batch-trl-template/batch-trl-template.component.html
Labels: bug

#970 fix(cb2-7834): added ids for add axle buttons on tyres and weights
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/weights/weights.component.html
Labels: bug

#972 fix(cb2-7913): hide certificate link on cancelled tests
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
Labels: bug

#973 fix(cb2-7914): adds vehicle configuration 'Other' to light vehicles
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
Labels: bug

#975 fix(cb2-7652): amend the cancel button text
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.html
Labels: bug

#976 fix(cb2-7926): adds custom defect in amend specialist test for car
  src/app/forms/templates/test-records/master.template.ts
Labels: bug

#979 fix(cb2-7932): change state systems to run only on first change
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#974 feat(CB2-7046): Batch update of existing vehicles
  src/app/features/tech-record/create-batch-trl/components/batch-trl-details/batch-trl-details.component.html
  src/app/features/tech-record/create-batch-trl/components/batch-trl-details/batch-trl-details.component.spec.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-details/batch-trl-details.component.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-results/batch-trl-results.component.html
  src/app/features/tech-record/create-batch-trl/components/batch-trl-results/batch-trl-results.component.spec.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-results/batch-trl-results.component.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-template/batch-trl-template.component.spec.ts
  src/app/features/tech-record/create-batch-trl/components/batch-trl-template/batch-trl-template.component.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/field-error-message/field-error-message.component.ts
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/utils/error-message-map.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/batch-create.reducer.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/batch-create.selectors.ts
Labels: enhancement

#980 fix(cb2-7946): do not add the trailer id as primary vrm
  src/app/features/tech-record/create/create-tech-record.component.ts
Labels: bug
