Repository dvsa/cvs-app-vtm, pull requests merged in 2023-01, with the labels that each got.

#775 fix(cb2-7100): fixed hgv make and model not appearing in search
  src/app/features/search/single-search-result/single-search-result.component.ts
Labels: bug

#777 fix(cb2-7090): seatbelt installation approval date format
  src/app/forms/templates/psv/psv-tech-record.template.ts
Labels: bug

#778 fix(cb2-7112): Verify and address issues raised on https://dvsa.atlassian.net/browse/CB2-6640
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
Labels: bug

#782 refactor(cb2-7151): simplify tech routing
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/tech-router-outlet/tech-router-outlet.component.html
  src/app/features/tech-record/components/tech-router-outlet/tech-router-outlet.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
Labels: enhancement

#784 fix(cb-7173): brake code prefix appears alongside dropdown
  src/app/forms/components/autocomplete/autocomplete.component.scss
Labels: bug

#779 feature(cb2-5696): change vehicle type from HGV to PSV
  src/app/features/tech-record/components/change-vehicle-type/change-vehicle-type.component.html
  src/app/features/tech-record/components/change-vehicle-type/change-vehicle-type.component.spec.ts
  src/app/features/tech-record/components/change-vehicle-type/change-vehicle-type.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/utils/enum-map.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: enhancement, sprint goal

#783 [Snyk] Upgrade rxjs from 7.6.0 to 7.8.0
  package-lock.json
  package.json
Labels: dependencies

#791 fix(cb2-7158): Updated record must submit to database passing all validation checks
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
Labels: bug, enhancement, sprint goal

#787 feat(cb2-7214): logic tweak to stop duplication of reason for creation
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
Labels: bug

#794 fix(cb2-7158): Update validations to align with api expectations
  src/app/forms/templates/psv/psv-dimensions.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tyres.template.ts
  src/app/forms/templates/psv/psv-weight.template.ts
Labels: enhancement

#796 fix(cb2-5696): fixed faults
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.html
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tyres.template.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/psv/psv-dimensions.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/psv/psv-weight.template.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
Labels: bug

#788 refactor(cb2-7174): add unique ids to components
  src/app/core/components/breadcrumbs/breadcrumbs.component.html
  src/app/core/components/footer/footer.component.html
  src/app/core/components/header/header.component.html
  src/app/features/home/components/home-button/home-button.component.html
  src/app/features/home/components/home-button/home-button.component.ts
  src/app/features/home/home.component.html
  src/app/features/search/multiple-search-results/multiple-search-results.component.html
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.html
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.html
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.html
  src/app/features/tech-record/components/tech-record-history/tech-record-history.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.html
  src/app/features/test-records/components/test-type-select/test-type-select.component.html
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
  src/app/forms/custom-sections/tyres/tyres.component.html
  src/app/forms/custom-sections/weights/weights.component.html
  src/app/shared/components/accordion-control/accordion-control.component.html
  src/app/shared/components/number-plate/number-plate.component.html
Labels: enhancement

#792 Allow EU Vehicle Category to be editable in a test
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
Labels: enhancement

#789 fix(cb2-7200): send the full vehicle object to the put endpoint
  .github/workflows/pr-checks.yml
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: bug

#802 fix(cb2-7192): fix how reference data labels are mapped
  src/app/services/reference-data/reference-data.service.spec.ts
  src/app/services/reference-data/reference-data.service.ts
Labels: bug

#801 feat(cb2-6631): show the model literal field on the psv body section
  src/app/forms/custom-sections/body/body.component.html
Labels: enhancement

#805 feat(cb2-397): add new vehicle body types
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/models/body-type-enum.ts
Labels: enhancement

#806 Allow EU Vehicle Category to be editable in a test
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug

#811 feat(cb2-5712): Create Vehicles
  src/app/app-routing.module.ts
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.spec.ts
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/features/create/create-routing.module.ts
  src/app/features/create/create.component.html
  src/app/features/create/create.component.spec.ts
  src/app/features/create/create.component.ts
  src/app/features/create/create.module.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/actions/technical-record-service.actions.spec.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
Labels: enhancement, sprint goal

#808 feat(cb2-7248): remove validation
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/body/body.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/custom-sections/weights/weights.component.ts
  src/app/forms/templates/car/car-tech-record.template.ts
  src/app/forms/templates/general/approval-type.template.ts
  src/app/forms/templates/general/audit.template.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/general/manufacturer.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-tyres.template.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/lgv/lgv-tech-record.template.ts
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
  src/app/forms/templates/psv/psv-approval-type.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/psv/psv-brakes.template.ts
  src/app/forms/templates/psv/psv-dda.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/psv/psv-tyres.template.ts
  src/app/forms/templates/psv/psv-weight.template.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/trl/trl-brakes.template.ts
  src/app/forms/templates/trl/trl-dimensions.template.ts
  src/app/forms/templates/trl/trl-purchaser.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/templates/trl/trl-tyres.template.ts
  src/app/forms/templates/trl/trl-weight.template.ts
  src/app/models/vehicle-tech-record.model.ts
Labels: bug

#812 fix(cb2-7354): tech record header actions
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.scss
Labels: improvement, refactor

#815 fix(cb2-7405): Front end defaults for numeric fields need to be null
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/hgv/hgv-weight.template.ts
  src/app/forms/templates/trl/trl-dimensions.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/forms/templates/trl/trl-weight.template.ts
Labels: bug, sprint goal

#817 fix(cb2-7398): submit new record doesn't show any validation
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
  src/app/features/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/psv/psv-tech-record.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
Labels: bug, sprint goal

#816 fix(cb2-7406): Unable to create a Trailer Tech Record due to missing field
  src/app/forms/custom-sections/dimensions/dimensions.component.html
  src/app/forms/templates/trl/trl-dimensions.template.ts
Labels: bug, enhancement, sprint goal

#818 chore(cb2-0000): bump vtm version to 1.4 ahead of release
  package.json
Labels: dependencies

#819 fix(cb2-7407): allow duplicate vins
  src/app/features/create/create.component.html
  src/app/features/create/create.component.spec.ts
  src/app/features/create/create.component.ts
Labels: bug

#810 feature(cb2-5698): Amend VRM
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.html
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.scss
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/tech-record/tech-record.module.ts
  src/app/models/vehicle-tech-record.model.ts
  src/mocks/psv-record.mock.ts
Labels: enhancement

#804 feat(cb2-7247): suggestive input
  src/app/app.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.spec.ts
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.ts
  src/app/forms/components/suggestive-input/suggestive-input.component.html
  src/app/forms/components/suggestive-input/suggestive-input.component.scss
  src/app/forms/components/suggestive-input/suggestive-input.component.spec.ts
  src/app/forms/components/suggestive-input/suggestive-input.component.ts
  src/app/forms/components/switchable-input/switchable-input.component.html
  src/app/forms/components/switchable-input/switchable-input.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-psv-hgv-light-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
  src/app/forms/templates/test-records/section-templates/visit/contingency-visit-section.template.ts
  src/app/forms/templates/test-records/section-templates/visit/visit-section.template.ts
Labels: enhancement
