Repository dvsa/cvs-app-vtm, pull requests merged in 2023-07, with the labels that each got.

#1065 Fix: cb2 8677: 404 received for some Reasons For Abandoning on saved abandoned test records
  src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
Labels: bug

#1066 feat(cb2-8091): removed the word driven
  src/app/forms/templates/motorcycle/motorcycle-tech-record.template.ts
Labels: enhancement

#1069 fix(cb2-8677): 404 received for some Reasons For Abandoning on saved abandoned test records
  src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: bug

#1070 feat(cb2-8099): save state for accordion sections
  src/app/features/search/search.component.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-results/batch-vehicle-results.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.spec.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.ts
  src/app/features/tech-record/create-batch/components/select-vehicle-type/select-vehicle-type.component.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/shared/components/accordion-control/accordion-control.component.spec.ts
  src/app/shared/components/accordion-control/accordion-control.component.ts
  src/app/shared/components/accordion/accordion.component.html
  src/app/shared/components/accordion/accordion.component.spec.ts
  src/app/shared/components/accordion/accordion.component.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.spec.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: enhancement

#1071 feat(cb2-8099): handle show/hide all sections on navigation
  src/app/shared/components/accordion-control/accordion-control.component.ts
Labels: enhancement

#1072 chore(*): add merge conflict tag action
  .github/workflows/tag-merge-conflicts.yml
Labels: improvement, task

#1073 chore(*): implement null values in merge conflict action
  .github/workflows/tag-merge-conflicts.yml
Labels: task

#1075 feat(cb2-8712): validate on blur
  src/app/forms/components/date/date.component.html
Labels: enhancement

#1076 fix(cb2-8718): tyre code lookup intermittently not working
  src/app/forms/custom-sections/tyres/tyres.component.ts
Labels: bug

#1074 fix(cb2-8751): user has to refresh the page to view amended details
  jest.config.js
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.spec.ts
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-change-visibility/tech-record-change-visibility.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.spec.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-template/batch-vehicle-template.component.html
  src/app/features/tech-record/create-batch/create-batch-routing.module.ts
  src/app/features/tech-record/create/components/hydrate-new-vehicle-record/hydrate-new-vehicle-record.component.html
  src/app/features/tech-record/create/create-tech-records-routing.module.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
Labels: bug, refactor

#1081 fix(cb2-8751): remove non-null assertion
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#1082 fix(cb2-8764): implements use of breadcrumbs within reference data administration
  src/app/features/reference-data/reference-data-add/reference-data-add.component.html
  src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
  src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
  src/app/features/reference-data/reference-data-amend/reference-data-amend.component.html
  src/app/features/reference-data/reference-data-amend/reference-data-amend.component.ts
  src/app/features/reference-data/reference-data-delete/reference-data-delete.component.html
  src/app/features/reference-data/reference-data-delete/reference-data-delete.component.spec.ts
  src/app/features/reference-data/reference-data-delete/reference-data-delete.component.ts
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.html
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.spec.ts
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.spec.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/reference-data/reference-data-routing.module.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.html
  src/app/features/reference-data/reference-data.module.ts
Labels: bug

#1083 fix(*): browser runs out of memory when editing some records
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
Labels: bug

#1085 fix(cb2-*): repair plate and letter sections
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.spec.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/tech-record-routing.module.ts
Labels: bug

#1084 chore(*): remove unused imports
  src/app/app.component.ts
  src/app/core/components/server-error/server-error.component.ts
  src/app/features/reference-data/reference-data-amend-history/reference-data-amend-history.component.ts
  src/app/features/reference-data/reference-data-amend/reference-data-amend.component.spec.ts
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.ts
  src/app/features/reference-data/reference-data-select-type/reference-data-select-type.component.spec.ts
  src/app/features/search/multiple-search-results/multiple-search-results.component.spec.ts
  src/app/features/search/single-search-result/single-search-result.component.spec.ts
  src/app/features/search/single-search-result/single-search-result.component.ts
  src/app/features/tech-record/components/tech-record-change-status/tech-record-change-status.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/create-batch/components/batch-vehicle-details/batch-vehicle-details.component.ts
  src/app/features/tech-record/create/create-tech-record.component.spec.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/features/test-records/amend/views/test-result-summary/test-result-summary.component.spec.ts
  src/app/features/test-records/components/test-type-select/test-type-select.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/features/test-records/create/views/create-test-type/create-test-type.component.spec.ts
  src/app/forms/components/field-error-message/field-error-message.component.ts
  src/app/forms/components/select/select.component.spec.ts
  src/app/forms/custom-sections/custom-defect/custom-defect.component.ts
  src/app/forms/custom-sections/letters/letters.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/forms/directives/app-trim-whitespace.directive.ts
  src/app/forms/templates/general/audit.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-vehicle-section-group5-lgv.template.ts
  src/app/forms/templates/trl/trl-purchaser.template.ts
  src/app/models/reference-data.model.ts
  src/app/resolvers/test-result/test-result.resolver.spec.ts
  src/app/services/batch-technical-record/batch-technical-record.service.spec.ts
  src/app/services/result-of-test/result-of-test.service.spec.ts
  src/app/services/result-of-test/result-of-test.service.ts
  src/app/services/test-records/test-records.service.spec.ts
  src/app/shared/components/input-spinner/input-spinner.component.ts
  src/app/shared/pipes/get-control-label/get-control-label.pipe.spec.ts
  src/app/shared/pipes/get-control-label/get-control-label.pipe.ts
  src/app/store/defects/selectors/defects.selectors.spec.ts
  src/app/store/global-error/reducers/global-error-service.reducer.spec.ts
  src/app/store/reference-data/actions/reference-data.actions.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.ts
  src/app/store/tech-record-search/effects/tech-record-search.effect.spec.ts
  src/app/store/tech-record-search/reducer/tech-record-search.reducer.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.spec.ts
  src/app/store/technical-records/selectors/technical-record-service.selectors.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
Labels: task

#1080 feat(cb2-8776): Fix error message not showing above field
  src/app/forms/components/date/date.component.html
  src/app/forms/components/date/date.component.ts
Labels: enhancement

#1087 fix(cb2-*): plate and letter gen fix
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: bug

#1088 feat(cb2-8776): fix error message not showing above field
  src/app/forms/components/date/date.component.ts
Labels: enhancement

#1091 feat(cb2-8711): add edit tech record button to bottom of tech record
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.html
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.spec.ts
  src/app/features/tech-record/components/edit-tech-record-button/edit-tech-record-button.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
Labels: enhancement

#1092 Feature/cb2 8144: ability to search reference data
  src/app/features/reference-data/reference-data-list/reference-data-list.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.scss
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
Labels: enhancement

#1093 feat(cb2-8711): move amend, submit, cancel buttons to right of screen
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.scss
Labels: enhancement

#1094 feat(cb2-8144): ability to search reference data
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
Labels: enhancement

#1095 feat(cb2-8144): ability to search reference data
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
Labels: enhancement

#1089 feat(cb2-8776): show error message not showing above field
  src/app/forms/components/date/date.component.ts
  src/app/forms/validators/date/date.validators.ts
Labels: enhancement
