Repository dvsa/cvs-app-vtm, pull requests merged in 2024-10, with the labels that each got.

#1603 fix(cb2-14238): ensure first test name is displayed even if record is current
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
Labels: bug

#1607 feat(cb2-12988): update favicon
  src/assets/icon/favicon.ico
Labels: enhancement

#1495 feat(cb2-11402): change display type
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group12and14.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10CentralDocs.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/old-contingency-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/old-contingency-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-lgv-template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group5-LGV.ts
Labels: enhancement

#1610 feat(cb2-11336): allow apostrophes in email addresses
  src/app/forms/validators/custom-validators/custom-validators.ts
Labels: enhancement

#1618 feat(cb2-12179): only allow adr tests on adr vehicles carrying danger…
  src/app/store/test-types/test-types.selectors.ts
Labels: enhancement

#1620 feat(cb2-13331): add smoke test k limit validation for decimals
  package-lock.json
  package.json
  src/app/forms/templates/test-records/section-templates/emissions/desk-based-emissions-section.template.ts
  src/app/forms/templates/test-records/section-templates/emissions/emissions-section.template.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: enhancement

#1622 fix(cb2-13831): retry on status of 0
  src/app/interceptors/delayed-retry/__tests__/delayed-retry.interceptor.spec.ts
  src/app/interceptors/interceptor.module.ts
Labels: bug

#1623 fix(cb2-14662): prevent non decimal characters
  src/app/directives/app-decimal-only/__tests__/app-decimal-only.directive.spec.ts
  src/app/directives/app-decimal-only/app-decimal-only.directive.ts
  src/app/forms/components/number-input/number-input.component.html
  src/app/forms/dynamic-forms.module.ts
Labels: bug

#1624 tech/fix-pack-ids : resolve missing id for pack
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.html
Labels: enhancement

#1625 fix(cb2-14242): do not default value of battery list applicable
  src/app/forms/templates/general/adr.template.ts
Labels: bug

#1627 chore(cb2-0000): upgrade packages
  package-lock.json
  package.json
Labels: task
