Repository dvsa/cvs-app-vtm, pull requests merged in 2024-02, with the labels that each got.

#1379 feat(cb2-10457): update the roles for desk based adr cert gen
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
  src/app/features/tech-record/tech-record-routing.module.ts
Labels: enhancement

#1380 feat(cb2-9990): update feature flags for adr epics
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement

#1376 fix(cb2-10591): uncomment custom views for TC2 and TC3 inspections
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/adr-tank-details-initial-inspection-view.component.html
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/adr-tank-details-subsequent-inspections-view.component.html
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/adr-summary.template.ts
  src/app/forms/templates/general/adr.template.ts
Labels: bug

#1382 fix(cb2-10824): do not alter value of tankStatement select when on summary review screen
  src/app/forms/custom-sections/adr/adr.component.ts
Labels: bug

#1381 feat(CB2-10726): Improve unit test coverage across VTM
  src/app/forms/components/approval-type/approval-type-focus-next.directive.spec.ts
  src/app/forms/components/approval-type/approval-type.component.spec.ts
Labels: enhancement

#1384 feat(cb2-10672): adr certificate generation is available when a pass result is selected for adr contingency tests
  src/app/features/tech-record/components/adr-generate-certificate/adr-generate-certificate.component.spec.ts
  src/app/forms/components/contingency-adr-generate-cert/contingency-adr-generate-cert.component.html
  src/app/forms/components/contingency-adr-generate-cert/contingency-adr-generate-cert.component.scss
  src/app/forms/components/contingency-adr-generate-cert/contingency-adr-generate-cert.component.spec.ts
  src/app/forms/components/contingency-adr-generate-cert/contingency-adr-generate-cert.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/interceptors/delayed-retry/delayed-retry.interceptor.spec.ts
  src/app/interceptors/delayed-retry/delayed-retry.interceptor.ts
  src/app/interceptors/interceptor.module.ts
  src/app/services/technical-record-http/technical-record-http.service.ts
  src/app/shared/components/test-certificate/test-certificate.component.spec.ts
  src/app/shared/directives/retrieve-document/retrieve-document.directive.spec.ts
  src/app/shared/directives/retrieve-document/retrieve-document.directive.ts
  src/app/store/app-store.module.ts
  src/app/store/retry-interceptor/actions/retry-interceptor.actions.ts
  src/app/store/retry-interceptor/retry-interceptor.module.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: enhancement

#1387 feat(cb2-10196): add in required standards section to IVA tests
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/forms/custom-sections/required-standards/required-standards.component.html
  src/app/forms/custom-sections/required-standards/required-standards.component.ts
  src/app/forms/custom-sections/required-standards/required-standards.spec.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/general/required-standards.template.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/models/test-results/test-result-required-standard.model.ts
Labels: enhancement

#1388 feat(cb2-10971): Add flag so required standards only show in dev
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement

#1385 feat(cb2-10930): refactor un subsequent inspections component
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.html
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.scss
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.spec.ts
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/adr/adr.validators.spec.ts
  src/app/forms/validators/adr/adr.validators.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1390 feat(cb2-10741): pull back and store Required Standards for a new IVA test
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/features/test-records/components/base-test-record/base-test-record.component.spec.ts
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/forms/components/required-standard-select/required-standard-select.component.html
  src/app/forms/components/required-standard-select/required-standard-select.component.ts
  src/app/forms/custom-sections/required-standards/required-standards.component.html
  src/app/forms/custom-sections/required-standards/required-standards.component.ts
  src/app/forms/custom-sections/required-standards/required-standards.spec.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/resolvers/required-standards/required-standards.resolver.spec.ts
  src/app/resolvers/required-standards/required-standards.resolver.ts
  src/app/services/loading/loading.service.ts
  src/app/services/required-standards/required-standards.service.ts
  src/app/store/app-store.module.ts
  src/app/store/index.ts
  src/app/store/required-standards/actions/required-standards.actions.spec.ts
  src/app/store/required-standards/actions/required-standards.actions.ts
  src/app/store/required-standards/effects/required-standards.effects.spec.ts
  src/app/store/required-standards/effects/required-standards.effects.ts
  src/app/store/required-standards/reducers/required-standards.reducer.spec.ts
  src/app/store/required-standards/reducers/required-standards.reducer.ts
  src/app/store/required-standards/required-standards.module.ts
  src/app/store/required-standards/selectors/required-standards.selector.spec.ts
  src/app/store/required-standards/selectors/required-standards.selector.ts
Labels: enhancement

#1392 feat(cb2-10421): create required standard select page
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/forms/components/required-standard-select/required-standard-select.component.html
  src/app/forms/components/required-standard-select/required-standard-select.component.scss
  src/app/forms/components/required-standard-select/required-standard-select.component.spec.ts
  src/app/forms/components/required-standard-select/required-standard-select.component.ts
  src/app/forms/custom-sections/required-standard/required-standard.component.html
  src/app/forms/custom-sections/required-standard/required-standard.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/store/required-standards/selectors/required-standards.selector.ts
Labels: enhancement

#1389 feat(cb2-8121): Remove all eslint warnings from unit tests
  .eslintrc
  src/app/app.component.spec.ts
  src/app/features/test-records/amend/components/test-amendment-history/test-amendment-history.component.spec.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.spec.ts
  src/app/forms/components/date/date.component.spec.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.spec.ts
  src/app/forms/custom-sections/abandon-dialog/abandon-dialog.component.spec.ts
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history.component-edit.spec.ts
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/date/date.validators.spec.ts
  src/app/services/batch-technical-record/batch-technical-record.service.spec.ts
  src/app/services/technical-record-http/technical-record-http.service.spec.ts
  src/app/store/defects/effects/defects.effects.spec.ts
  src/app/store/reference-data/effects/reference-data.effects.spec.ts
  src/app/store/tech-record-search/effects/tech-record-search.effect.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/app/store/test-records/selectors/test-records.selectors.spec.ts
  src/app/store/test-stations/effects/test-stations.effects.spec.ts
  src/app/store/test-types/effects/test-types.effects.spec.ts
  src/index.html
Labels: enhancement

#1397 fix(cb2-11013): prevent fitment code being cut-off on larger viewports
  src/app/forms/custom-sections/tyres/tyres.component.html
Labels: bug

#1394 fix(cb2-10560): shows the you must provide a new vrm error if you add a third mark
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#1396 fix(cb2-9198): correctly name application id key so its saved in the db
  src/app/store/technical-records/effects/technical-record-service.effects.ts
Labels: bug

#1399 feat(cb2-10672): adr certificate generation is available when a pass result is selected for adr contingency tests
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
Labels: enhancement

#1401 feat(cb2-10197): update custom defects to additional defects on iva/msva
  src/app/features/test-records/components/base-test-record/base-test-record.component.html
  src/app/forms/custom-sections/custom-defect/custom-defect.component.html
  src/app/forms/custom-sections/custom-defect/custom-defect.component.ts
  src/app/forms/custom-sections/custom-defects/custom-defects.component.html
  src/app/forms/custom-sections/custom-defects/custom-defects.component.spec.ts
  src/app/forms/custom-sections/custom-defects/custom-defects.component.ts
  src/app/forms/custom-sections/required-standard/required-standard.component.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/additionalDefects/additional-defects-section.template.ts
Labels: enhancement

#1402 feat(cb2-10726): improve unit test coverage
  src/app/app.component.spec.ts
  src/app/features/tech-record/components/adr-generate-certificate/adr-generate-certificate.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.spec.ts
Labels: enhancement

#1400 fix(cb2-11085): fix styling bug with tags
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.scss
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/text-input/text-input.component.scss
Labels: bug

#1406 fix(cb2-10602): repair PRS toggle on amend for RS
  src/app/forms/custom-sections/required-standard/required-standard.component.ts
Labels: bug

#1410 feat(cb2-10198): cert no. required on iva/msva pass/prs
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
Labels: enhancement

#1404 feat(cb2-9659): delete empty required standards object from payload
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.spec.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/services/test-records/test-records.service.ts
  src/app/store/test-records/actions/test-records.actions.ts
  src/app/store/test-records/reducers/test-records.reducer.spec.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
Labels: enhancement

#1408 feat(cb2-10920): Angular 16 to 17
  .eslintrc
  .github/workflows/deploy.yml
  .github/workflows/pr-checks.yml
  README.md
  package-lock.json
  package.json
  src/app/features/reference-data/reference-data-add/reference-data-add.component.ts
  src/app/features/reference-data/reference-data-amend/reference-data-amend.component.ts
  src/app/features/reference-data/reference-data-delete/reference-data-delete.component.ts
  src/app/features/reference-data/reference-data-deleted-list/reference-data-deleted-list.component.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/features/tech-record/components/tech-record-amend-reason/tech-record-amend-reason.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/test-record-summary/test-record-summary.component.spec.ts
  src/app/features/test-records/amend/components/test-amendment-history/test-amendment-history.component.spec.ts
  src/app/features/test-records/components/test-type-select/test-type-select.component.spec.ts
  src/app/forms/validators/custom-async-validators.spec.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/services/user-service/user-service.spec.ts
  src/app/services/user-service/user-service.ts
  src/app/shared/components/tag/tag.component.ts
  src/app/shared/pipes/ref-data-decode/ref-data-decode.pipe.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/app/store/test-records/reducers/test-records.reducer.spec.ts
  src/app/store/test-records/selectors/test-records.selectors.spec.ts
  src/mocks/custom-defect.mock.ts
  src/mocks/hgv-record.mock.ts
  src/mocks/lgv-record.mock.ts
  src/mocks/mock-defects.ts
  src/mocks/mock-test-result.ts
  src/mocks/test-result.mock.ts
  src/mocks/test-type-category.mock.ts
  src/mocks/test-type.mock.ts
  src/mocks/trl-record.mock.ts
  tsconfig.json
Labels: enhancement

#1409 feat(cb2-11091): show adr certificate generation in vtm
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: task

#1407 feat(cb2-8123): attempt of refactor magic string
  src/app/app-routing.module.ts
  src/app/features/reference-data/reference-data-routing.module.ts
  src/app/features/search/search-routing.module.ts
  src/app/features/tech-record/create-batch/create-batch-routing.module.ts
  src/app/features/tech-record/create/create-tech-records-routing.module.ts
  src/app/features/tech-record/tech-record-routing.module.ts
  src/app/features/test-records/amend/amend-test-records-routing.module.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/models/routes.enum.ts
Labels: enhancement

#1412 feat(cb2-*): update version and reintroduce role
  package.json
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.html
Labels: enhancement
