Repository dvsa/cvs-app-vtm, pull requests merged in 2024-01, with the labels that each got.

#1345 chore(cb2-10329): refactor to use dev as default config for feature flags
  .env.example
  setenv.ts
  src/app/services/feature-toggle-service/feature-toggle-service.spec.ts
  src/app/services/feature-toggle-service/feature-toggle-service.ts
Labels: task

#1343 fix(cb2-10321): fix adr warnings
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1344 fix(cb2-10328): refactor adr component
  src/app/core/components/global-error/global-error.service.ts
  src/app/forms/custom-sections/adr/adr.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/adr-summary.template.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/services/adr/adr.service.spec.ts
  src/app/services/adr/adr.service.ts
Labels: bug

#1339 fix(cb2-8121): general improvements to the type system
  src/app/features/tech-record/components/tech-record-amend-vrm-reason/tech-record-amend-vrm-reason.component.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.spec.ts
  src/app/features/tech-record/create/create-tech-record.component.ts
  src/app/forms/custom-sections/adr-examiner-notes-history/adr-examiner-notes-history.component.ts
  src/app/forms/custom-sections/approval-type/approval-type.component.ts
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
  src/app/forms/custom-sections/tyres/tyres.component.spec.ts
  src/app/forms/custom-sections/tyres/tyres.component.ts
  src/app/models/vehicle-tech-record.model.ts
  src/app/services/axles/axles.service.ts
  src/mocks/psv-record.mock.ts
Labels: bug

#1346 fix(cb2-10321): ensure validation is run only when control is visible
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1347 fix(cb2-10343): correct logic for determining whether to autopopulate…
  src/app/forms/custom-sections/adr/adr.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.ts
  src/app/services/adr/adr.service.ts
Labels: bug

#1351 feat(cb2-10211): only run validation when control is visible
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
  src/app/forms/templates/general/adr.template.ts
Labels: enhancement

#1353 fix(cb2-10433): repair tyre checks on plate validation
  src/app/forms/custom-sections/plates/plates.component.spec.ts
  src/app/forms/custom-sections/plates/plates.component.ts
Labels: bug

#1354 feat(cb2-9882): Better global error message displaying
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
Labels: enhancement

#1355 fix(cb2-10441): fix reference number incorrectly display
  src/app/forms/templates/general/adr.template.ts
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#1356 feat(cb2-10112): custom un numbers validator
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1357 fix(cb2-10112): make max length validator actually work
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1358 feat(cb2-10467): Update snyk dependencies
  package-lock.json
  package.json
Labels: enhancement

#1359 refactor(cb2-10039): remove custom id not required for fields since v3
  src/app/forms/templates/general/adr-summary.template.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/templates/general/applicant-details.template.ts
  src/app/forms/templates/general/manufacturer.template.ts
  src/app/forms/templates/trl/trl-purchaser.template.ts
Labels: refactor

#1361 fix(cb2-10499): add data resolver to create-batch route
  src/app/features/tech-record/create-batch/create-batch-routing.module.ts
Labels: bug

#1367 feat(cb2-10129): Odometer reading marked as optional on IVA
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/contingency-m1-iva-vehicle-section.template.ts
  src/app/forms/utils/error-message-map.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
Labels: enhancement

#1369 fix(cb2-10555): fix listStatementApplicable not be set null
  src/app/store/technical-records/reducers/technical-record-service.reducer.ts
Labels: bug

#1370 feat(cb2-10586): remove 5th wheel coupling from HGV plates
  src/app/forms/models/plateRequiredFields.model.ts
  src/app/forms/templates/hgv/hgv-dimensions.template.ts
Labels: enhancement

#1371 feat(cb2-8121): improve test coverage
  src/app/services/documents/documents.service.spec.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/store/technical-records/effects/technical-record-service.effects.spec.ts
Labels: enhancement

#1372 feat(cb2-10521): change adr brake endurance weight unit of measurement to tonnes on a technical record
  package-lock.json
  package.json
  src/app/forms/templates/general/adr.template.ts
Labels: enhancement

#1373 feat(cb2-8121): more unit tests + css fixeseat(cb2-8121): more unit tests + css fixes
  src/app/forms/components/select/select.component.html
  src/app/forms/components/select/select.component.scss
  src/app/forms/custom-sections/psv-brakes/psv-brakes.component.html
  src/app/forms/custom-sections/weights/weights.component.spec.ts
  src/app/forms/custom-sections/weights/weights.component.ts
Labels: enhancement
