Repository dvsa/cvs-app-vtm, pull requests merged in 2024-08, with the labels that each got.

#1528 feat(cb2-13299): VTM - Pass and issue Documents Centrally for a Notifiable Alteration test
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group8Notifiable.template.ts
Labels: enhancement

#1529 feat(13396):lec removed
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
Labels: enhancement

#1531 feat(cb2-13176): only show hint text for pass/prs results
  src/app/forms/templates/test-records/section-templates/notes/adr-notes-section.template.ts
Labels: enhancement

#1533 fix(cb2-13506): use correct notes section on amending ADR tests
  src/app/forms/templates/test-records/master.template.ts
Labels: bug

#1530 feat(cb2-13455): VTM - Pass and issue Documents Centrally (additional test type ids)
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10CentralDocs.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10CentralDocs.template.ts
Labels: enhancement

#1543 fix(cb2-13164): add issue docs centrally to TIR test types
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
Labels: bug

#1547 refactor(gha-1): decouple sonar from pr checks
  .github/workflows/pr-checks.yml
  .github/workflows/sonar-scan.yml
Labels: refactor

#1546 chore(testing-1): exclude non functional files from jest path/coverage
  .github/workflows/pr-checks.yml
  jest.config.js
Labels: task

#1536 chore(nodeupgrade-1): node upgrade
  .nvmrc
  package-lock.json
  package.json
Labels: task

#1553 chore(dep-1): angular 18 upgrade
  .github/workflows/pr-checks.yml
  angular.json
  package-lock.json
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/features/tech-record/components/adr-generate-certificate/adr-generate-certificate.component.spec.ts
  src/app/features/tech-record/components/tech-record-amend-vrm/tech-record-amend-vrm.component.ts
  src/app/features/tech-record/components/tech-record-generate-plate/tech-record-generate-plate.component.spec.ts
  src/app/features/test-records/amend/views/test-record/test-record.component.ts
  src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
  src/app/forms/utils/error-message-map.spec.ts
  src/app/services/loading/loading.service.ts
  src/app/shared/components/pagination/pagination.component.spec.ts
  src/app/store/defects/effects/defects.effects.ts
  src/app/store/reference-data/effects/reference-data.effects.ts
  src/app/store/required-standards/effects/required-standards.effects.ts
  src/app/store/tech-record-search/effects/tech-record-search.effect.ts
  src/app/store/technical-records/actions/technical-record-service.actions.ts
  src/app/store/technical-records/effects/technical-record-service.effects.ts
  src/app/store/test-records/effects/test-records.effects.ts
  src/app/store/test-stations/effects/test-stations.effects.ts
  src/app/store/test-types/effects/test-types.effects.ts
  tsconfig.json
Labels: task

#1557 fix(cb2-13684): prevent lost of tech record status when filtering test types
  src/app/features/test-records/components/base-test-record/base-test-record.component.ts
  src/app/store/test-types/selectors/test-types.selectors.spec.ts
  src/app/store/test-types/selectors/test-types.selectors.ts
Labels: bug

#1554 fix(cb2-13615): ensure we're not showing child if parent is also hidden
  src/app/forms/validators/custom-validators.ts
Labels: bug

#1559 fix(cb2-13455): ensure certificate number is present
  src/app/store/test-records/reducers/test-records.reducer.ts
Labels: bug

#1562 chore(gha-1): update action versions for deploy flow
  .github/workflows/deploy.yml
Labels: task

#1564 fix(gha-1): update artifact path
  .github/workflows/deploy.yml
Labels: bug

#1566 feat(cb2-13234): Add guidance notes links within VTM
  package-lock.json
  package.json
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.scss
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/services/dynamic-form.types.ts
  src/app/forms/templates/general/adr.template.ts
Labels: enhancement

#1534 feat(cb2-8973): Add test codes to test names
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/app/store/test-records/effects/test-records.effects.ts
Labels: enhancement
