Repository dvsa/cvs-app-vtm, pull requests merged in 2024-12, with the labels that each got.

#1662 feat(cb2-15344): show chassis make and model for PSVs on review screen
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/forms/templates/tech-records/vehicle-summary.template.ts
Labels: enhancement

#1663 feat(CB2-14743): add recalls banner
  package-lock.json
  package.json
  src/app/features/test-records/amend/views/confirm-cancellation/__tests__/confirm-cancellation.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/forms/templates/small-trailer/small-trailer-tech-record.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group12and14.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group9And10CentralDocs.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/old-contingency-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/old-contingency-specialist-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1-PSV.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group1And4-HGV-TRL.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group3.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-PSV.template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group4-lgv-template.ts
  src/app/forms/templates/test-records/section-templates/test/desk-based/desk-based-test-section-group5-LGV.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/old-specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/old-specialist-test-section-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group3And4.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group5.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group12And14.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group3And4And8.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group6And11.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group9And10CentralDocs.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section.template.ts
  src/app/forms/templates/trl/trl-tech-record.template.ts
  src/app/models/test-results/test-result.model.ts
  src/app/resolvers/recalls/__tests__/recalls.resolver.spec.ts
  src/app/resolvers/recalls/recalls.resolver.ts
  src/app/services/http/http.service.ts
  src/app/store/test-records/test-records.actions.ts
  src/app/store/test-records/test-records.effects.ts
  src/app/store/test-records/test-records.reducer.ts
  src/styles.scss
Labels: enhancement

#1664 feat(cb2-14743): remove recalls from test submission for non HGV/PSV/TRL tests
  src/app/resolvers/recalls/recalls.resolver.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: enhancement

#1670 fix(CB2-14459): fix additional disabled properties added by mistake
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.html
  src/app/forms/custom-sections/body-section/body-section-edit/body-section-edit.component.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.ts
Labels: merge conflict

#1683 feat(adr-tank-inspections-fix): fix inspections
  src/app/forms/custom-sections/adr-section/adr-section-edit/__tests__/adr-section-edit.component.spec.ts
  src/app/forms/custom-sections/adr-section/adr-section-edit/adr-section-edit.component.ts
Labels: enhancement

#1660 feat(cb2-14451): DFS Vehicle Summary Section
  src/app/directives/govuk-form-group/govuk-form-group.directive.ts
  src/app/directives/govuk-input/govuk-input.directive.ts
  src/app/directives/govuk-radio/govuk-radio.directive.ts
  src/app/directives/govuk-select/govuk-select.directive.ts
  src/app/directives/tag/tag.directive.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/forms/components/govuk-checkbox-group/govuk-checkbox-group.component.html
  src/app/forms/components/govuk-checkbox-group/govuk-checkbox-group.component.scss
  src/app/forms/components/govuk-checkbox-group/govuk-checkbox-group.component.ts
  src/app/forms/components/govuk-form-group-date/govuk-form-group-date.component.html
  src/app/forms/components/govuk-form-group-date/govuk-form-group-date.component.scss
  src/app/forms/components/govuk-form-group-date/govuk-form-group-date.component.ts
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.html
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.scss
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.ts
  src/app/forms/components/govuk-form-group-radio/govuk-form-group-radio.component.html
  src/app/forms/components/govuk-form-group-radio/govuk-form-group-radio.component.scss
  src/app/forms/components/govuk-form-group-radio/govuk-form-group-radio.component.ts
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.html
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.scss
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.ts
  src/app/forms/custom-sections/adr-section/__tests__/adr-section.component.spec.ts
  src/app/forms/custom-sections/adr-section/adr-section-edit/__tests__/adr-section-edit.component.spec.ts
  src/app/forms/custom-sections/adr-section/adr-section-view/adr-section-view.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/__tests__/vehicle-section-edit.component.spec.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.scss
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section-summary/vehicle-section-summary.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-summary/vehicle-section-summary.component.scss
  src/app/forms/custom-sections/vehicle-section/vehicle-section-summary/vehicle-section-summary.component.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section-view/vehicle-section-view.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-view/vehicle-section-view.component.scss
  src/app/forms/custom-sections/vehicle-section/vehicle-section-view/vehicle-section-view.component.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section.component.scss
  src/app/forms/custom-sections/vehicle-section/vehicle-section.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/hgv/hgv-tech-record.template.ts
  src/app/forms/validators/common-validators.service.ts
  src/app/models/options.model.ts
  src/app/pipes/multi-option/__tests__/multi-option.pipe.spec.ts
  src/app/pipes/multi-option/multi-option.pipe.ts
  src/app/shared/shared.module.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
  src/global-styles.scss
  src/styles.scss
Labels: enhancement

#1688 fix(handle-recalls-failure): handle recalls failure
  src/app/interceptors/interceptor.module.ts
Labels: bug

#1694 fix(CB2-12720): show validation immediately
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts
Labels: bug

#1686 feat(feat/CB2-15486): spelling error corrected
  src/app/forms/custom-sections/adr-section/adr-section-view/adr-section-view.component.html
Labels: enhancement

#1690 fix(CB2-15660): fix issue where delete of tc3 inspection was not propagated
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#1693 feat(cb2-15580): add ability to download VTP and VTG 12 documents for abandoned tests
  package-lock.json
  package.json
  src/app/features/test-records/components/vehicle-header/__tests__/vehicle-header.component.spec.ts
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.scss
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/models/testTypeId.enum.ts
Labels: enhancement
