Repository dvsa/cvs-app-vtm, pull requests merged in 2024-07, with the labels that each got.

#1507 chore(dependency): remove cypress config and dependencies
  cypress/e2e/techRecord/HGV/hgv.cy.ts
  cypress/e2e/techRecord/LGV/lgv.cy.ts
  cypress/e2e/techRecord/PSV/psv.cy.ts
  cypress/e2e/techRecord/TRL/trl.cy.ts
  cypress/e2e/testResults/HGV/tests.cy.ts
  cypress/e2e/testResults/LGV/DBA.cy.ts
  cypress/e2e/testResults/TRL/tests.cy.ts
  cypress/fixtures/433.json
  cypress/fixtures/hgv-testable.json
  cypress/fixtures/lgv.json
  cypress/fixtures/psv.json
  cypress/fixtures/trl-testable.json
  cypress/support/commands.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: task

#1509 chore(husky): update command to remove deprecation warning
  package.json
Labels: task

#1517 fix(cb2-12972): allow users to submit cancelled iva tests
  src/app/features/test-records/amend/views/confirm-cancellation/confirm-cancellation.component.ts
Labels: bug

#1511 chore(storybook-1): removal of storybook dependencies and commands
  package-lock.json
  package.json
Labels: task

#1510 chore(cypress-1): further removal of cypress and any config related
  .eslintignore
  .gitignore
  cypress.config.ts
  setenv.ts
  sonar-project.properties
  tsconfig.json
Labels: task

#1520 patch: Deployment Workflow
  .github/workflows/deploy-prod.yml
Labels: actions

#1519 feat(cb2-13176): VTM - Add guidance for handling documents issued centrally
  src/app/forms/models/async-validators.enum.ts
  src/app/forms/models/validators.enum.ts
  src/app/forms/services/dynamic-form.service.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/section-templates/notes/adr-notes-section.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group15and16.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group2.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group15And16.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/validators/custom-async-validators.ts
  src/app/forms/validators/custom-validators.spec.ts
  src/app/forms/validators/custom-validators.ts
  src/app/models/test-types/test-type.model.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
Labels: enhancement

#1521 feat(cb2-13299): VTM - Pass and issue Documents Centrally for a Notifiable Alteration test
  src/app/forms/models/testTypeId.enum.ts
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group8Notifiable.template.ts
Labels: enhancement

#1526 chore(version-bump): bump version
  package.json
Labels: task
