Repository dvsa/cvs-app-vtm, pull requests merged in 2024-09, with the labels that each got.

#1567 feat(cb2-13762): VTM - Pass and issue Documents Centrally (Additional test type id's to be added)
  src/app/forms/models/testTypeId.enum.ts
  src/app/models/test-types/test-type.model.ts
  src/app/store/test-records/reducers/test-records.reducer.ts
Labels: enhancement

#1569 fix(cb2-13234): reword text for link
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
Labels: bug

#1535 feat(cb2-10711): First Test and First Test Retest must always be available on provisional tech records for HGVs
  src/app/store/test-types/selectors/test-types.selectors.ts
Labels: enhancement

#1568 feat(cb2-13762): add test codes to test names
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.ts
  src/app/features/test-records/create/create-test-records-routing.module.ts
  src/app/resolvers/test-code/test-code.resolver.ts
  src/app/resolvers/test-result/test-result.resolver.ts
  src/app/services/technical-record/technical-record.service.ts
  src/app/store/test-records/effects/test-records.effects.spec.ts
  src/app/store/test-records/effects/test-records.effects.ts
Labels: enhancement

#1572 fix(cb2-8973): use correct vehicle class
  src/app/interceptors/error-handling/error-handling.interceptor.ts
  src/app/interceptors/interceptor.module.ts
  src/app/resolvers/test-code/test-code.resolver.ts
  src/app/services/technical-record/technical-record.service.spec.ts
  src/app/services/technical-record/technical-record.service.ts
Labels: bug

#1576 fix(cb2-13835): handle undefined roles
  src/app/services/user-service/user-service.ts
  src/app/store/user/user-service.actions.ts
  src/app/store/user/user-service.reducer.ts
Labels: bug

#1577 fix(cb2-13837): handle fetching a specific trailer make which is miss…
  src/app/features/reference-data/reference-data-list/__tests__/reference-data-list.component.spec.ts
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/store/reference-data/__tests__/reference-data.selectors.spec.ts
  src/app/store/reference-data/reference-data.selectors.ts
Labels: bug

#1579 fix(cb2-13830): fix NG0600
  src/app/forms/custom-sections/body/__tests__/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.ts
Labels: bug

#1578 fix(cb2-13838): fix sentry errors when refreshing ref data admin
  src/app/features/reference-data/reference-data-list/reference-data-list.component.html
  src/app/features/reference-data/reference-data-list/reference-data-list.component.ts
  src/app/models/reference-data.model.ts
  src/app/store/reference-data/reference-data.selectors.ts
Labels: bug

#1580 fix(cb2-13941): handle when current axles is falsy
  src/app/forms/custom-sections/tyres/tyres.component.ts
Labels: bug

#1581 fix(cb2-13940): check type of value before using it
  src/app/forms/components/checkbox-group/checkbox-group.component.ts
Labels: bug

#1582 feat(cb2-13794): Fix memo text
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/templates/general/adr-summary.template.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/services/dynamic-forms/dynamic-form.types.ts
Labels: enhancement

#1583 fix(cb2-13119): fix editing additional examiner notes
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history-edit.component.html
Labels: bug

#1586 chore(cb2-1): bump biome config
  .eslintignore
  .eslintrc
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  src/app/features/tech-record/components/tech-record-amend-vin/tech-record-amend-vin.component.ts
  src/app/features/tech-record/components/tech-record-generate-letter/tech-record-generate-letter.component.ts
  src/app/features/tech-record/components/tech-record-search-tyres/tech-record-search-tyres.component.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.ts
  src/app/features/tech-record/components/vehicle-technical-record/vehicle-technical-record.component.ts
  src/app/forms/validators/custom-async-validator/__tests__/custom-async-validators.spec.ts
  src/app/services/dynamic-forms/dynamic-form.service.ts
  src/app/store/technical-records/batch-create.reducer.ts
  tslint.json
Labels: task

#1590 feat(cb2-13667): capitalise cert numbers for iva/msva
  src/app/forms/components/base-control/__tests__/base-control.component.spec.ts
  src/app/forms/components/base-control/base-control.component.ts
  src/app/forms/components/text-input/__tests__/text-input.component.spec.ts
  src/app/forms/components/text-input/text-input.component.html
  src/app/forms/components/text-input/text-input.component.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1.template.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1.template.ts
  src/app/models/testTypeId.enum.ts
  src/app/services/dynamic-forms/dynamic-form.types.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: enhancement

#1591 fix(cb2-13791): workaround for migrated data
  src/app/forms/custom-sections/adr/__tests__/adr.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.ts
  src/app/services/adr/__tests__/adr.service.spec.ts
  src/app/services/adr/adr.service.ts
Labels: bug

#1592 fix(cb2-14000): handle response type text correctly
  src/app/services/http/http.service.ts
Labels: bug

#1584 feat(cb2-13813): enable issue docs centrally for test type 67
  src/app/models/testTypeId.enum.ts
Labels: enhancement

#1593 feat(cb2-11687): Hide Explosive Type 2 and 3 from Permitted Dangerous Goods when ADR Body Type includes 'Tank' or 'Battery'
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.ts
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.html
  src/app/forms/components/dynamic-form-group/dynamic-form-group.component.ts
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/__tests__/adr-permitted-dangerous-goods.component.spec.ts
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.html
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.scss
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.ts
  src/app/forms/custom-sections/adr/adr.component.html
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/templates/general/adr.template.ts
Labels: enhancement

#1594 feat(cb2-13814): remove 199 from central docs list
  src/app/models/testTypeId.enum.ts
Labels: enhancement

#1595 fix(cb2-11687): Fix empty adr details causing filter to break
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.ts
Labels: bug

#1596 chore(lint-staged): run linter on pre-commit
  .husky/pre-commit
  package-lock.json
  package.json
Labels: task

#1597 chore(cb2-0000): update packages
  package-lock.json
  package.json
Labels: task
