Repository dvsa/cvs-app-vtm, pull requests merged in 2025-05, with the labels that each got.

#1858 feat(CB2-16340): enable purchasers and brakes in prod envs
  src/assets/featureToggle.int.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement

#1859 chore(CB2-14487): - letters import removed
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
Labels: task

#1861 feat(CB2-17450): add IM numbers to defects selector
  src/app/forms/components/defect-select/defect-select.component.html
Labels: enhancement

#1860 feat(cb2-17487): persist certificate number for non-voluntary IVA HGV and TRL tests.
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-specialist-group1HgvAndTrl.ts
  src/app/forms/templates/test-records/section-templates/test/specialist/specialist-test-section-group1HgvAndTrl.ts
  src/app/forms/validators/custom-async-validator/custom-async-validators.ts
  src/app/models/testTypeId.enum.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: enhancement

#1864 feat(CB2-14499-audit): audit component
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/audit-section/audit-section-summary/audit-section-summary.component.html
  src/app/forms/custom-sections/audit-section/audit-section-summary/audit-section-summary.component.scss
  src/app/forms/custom-sections/audit-section/audit-section-summary/audit-section-summary.component.ts
  src/app/forms/custom-sections/audit-section/audit-section-view/audit-section-view.component.html
  src/app/forms/custom-sections/audit-section/audit-section-view/audit-section-view.component.scss
  src/app/forms/custom-sections/audit-section/audit-section-view/audit-section-view.component.ts
  src/app/forms/custom-sections/audit-section/audit-section.component.html
  src/app/forms/custom-sections/audit-section/audit-section.component.scss
  src/app/forms/custom-sections/audit-section/audit-section.component.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement

#1867 feat(CB2-14458): dfs adr cert refactor
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-edit/adr-certs-section-edit.component.html
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-edit/adr-certs-section-edit.component.scss
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-edit/adr-certs-section-edit.component.ts
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-view/__tests__/adr-certs-section-view.component.spec.ts
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-view/adr-certs-section-view.component.html
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-view/adr-certs-section-view.component.scss
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section-view/adr-certs-section-view.component.ts
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section.component.html
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section.component.scss
  src/app/forms/custom-sections/adr-certs-section/adr-certs-section.component.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement

#1869 fix(CB2-16954): fix loading spinner on test create
  src/app/resolvers/recalls/recalls.resolver.ts
  src/app/store/test-records/__tests__/test-records.effects.spec.ts
  src/app/store/test-records/__tests__/test-records.reducer.spec.ts
  src/app/store/test-records/test-records.actions.ts
  src/app/store/test-records/test-records.effects.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: bug

#1871 fix(CB2-17793): ensure disabled fields propagate their values
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
Labels: bug

#1872 fix(CB2-17795): fix psv axles issue
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/weights-section/weights-section-edit/weights-section-edit.component.ts
  src/app/forms/custom-sections/weights-section/weights-section.component.html
  src/app/forms/custom-sections/weights-section/weights-section.component.ts
Labels: bug

#1874 fix(CB2-17406): render correct property
  src/app/forms/custom-sections/dda-section/dda-section-summary/dda-section-summary.component.html
  src/app/forms/custom-sections/dda-section/dda-section-view/dda-section-view.component.html
Labels: bug

#1875 fix(CB2-17409): change input sizes
  src/app/forms/custom-sections/documents-section/documents-section-edit/documents-section-edit.component.html
Labels: bug

#1876 fix(cb2-17409): allow saving empty values as null
  src/app/forms/components/govuk-form-group-autocomplete/govuk-form-group-autocomplete.component.ts
  src/app/forms/custom-sections/documents-section/documents-section-edit/documents-section-edit.component.html
Labels: bug

#1881 feat(cb2-0000): add automation ids
  src/app/forms/custom-sections/brakes-section/brakes-section-edit/brakes-section-edit.component.html
Labels: enhancement

#1886 fix(CB2-16933): display abandon reasons on separate lines
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/global-styles.scss
Labels: bug

#1887 feat(CB2-16684): enable hgv and psv eu vehicle category filtering
  src/app/forms/validators/custom-async-validator/custom-async-validators.ts
Labels: enhancement

#1884 fix(CB2-17857): ensure brake forces are correctly calculated
  src/app/forms/custom-sections/weights-section/weights-section-edit/weights-section-edit.component.ts
Labels: bug

#1891 feat(CB2-16933): use regex
  src/app/forms/components/view-list-item/view-list-item.component.html
  src/app/forms/components/view-list-item/view-list-item.component.ts
Labels: enhancement

#1892 fix(CB2-17326): remove old notes and body dfs sections
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/body/__tests__/body.component.spec.ts
  src/app/forms/custom-sections/body/body.component.html
  src/app/forms/custom-sections/body/body.component.scss
  src/app/forms/custom-sections/body/body.component.ts
  src/app/forms/templates/general/hgv-trl-body.template.ts
  src/app/forms/templates/general/notes.template.ts
  src/app/forms/templates/psv/psv-body.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/store/technical-records/__tests__/technical-record-service.effects.spec.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: bug

#1894 fix(CB2-17415): use textarea and change label to name
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-edit/manufacturer-section-edit.component.html
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-edit/manufacturer-section-edit.component.ts
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-summary/manufacturer-section-summary.component.html
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-view/manufacturer-section-view.component.html
Labels: bug

#1896 fix(CB2-17415): fix issues raised for manufacturer section
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-edit/manufacturer-section-edit.component.html
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-edit/manufacturer-section-edit.component.ts
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-summary/manufacturer-section-summary.component.html
  src/app/forms/custom-sections/manufacturer-section/manufacturer-section-view/manufacturer-section-view.component.html
Labels: bug
