Repository dvsa/cvs-app-vtm, pull requests merged in 2025-01, with the labels that each got.

#1697 fix(CB2-14452): reset autocomplete to default value when cleared
  src/app/forms/components/autocomplete/__tests__/autocomplete.component.spec.ts
  src/app/forms/components/autocomplete/autocomplete.component.ts
Labels: bug

#1699 fix(CB2-15741): fix correct small trl eu vehicle cat
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.html
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.ts
  src/app/models/options.model.ts
Labels: bug

#1701 feat(feat/CB2-15735): bug fixed
  src/app/forms/custom-sections/vehicle-section/vehicle-section-view/vehicle-section-view.component.html
Labels: enhancement

#1700 feat(cb2-15734): hide required tag for subclass for small trl
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.html
Labels: enhancement

#1698 fix(cb2-15660): fix un numbers
  src/app/forms/custom-sections/adr-section/adr-section-edit/adr-section-edit.component.ts
Labels: bug

#1717 fix(CB2-15892-fix-function-code): fix function code (#1716)
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.ts
Labels: bug

#1722 feat(CB2-14199): cleanse ADR details
  src/app/resolvers/tech-record-clean/tech-record-clean.resolver.ts
Labels: enhancement

#1724 feat(CB2-14817): Hide adr retest category if dangerous goods not selected
  src/app/store/test-types/test-types.selectors.ts
Labels: enhancement

#1728 feat(cb2-15209): remove custom defects from specific test type id groups
  src/app/forms/templates/test-records/create-master.template.ts
  src/app/forms/templates/test-records/master.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/contingency/contingency-test-section-group8Notifiable.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group5And13.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group7.template.ts
  src/app/forms/templates/test-records/section-templates/test/test-section-group8Notifiable.template.ts
  src/app/store/test-records/test-records.reducer.ts
Labels: enhancement

#1732 feat(feat/cb2-16017): removed required label
  src/app/forms/custom-sections/vehicle-section/vehicle-section-edit/vehicle-section-edit.component.html
Labels: enhancement

#1704 fix(CB2-15775): show UN numbers on review
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.html
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.ts
Labels: bug

#1736 chore(cb2-0000): bump version to 1.31
  package-lock.json
  package.json
Labels: task

#1735 feat(cb2-14450-weights-dfs): weights and tyres
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.html
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.ts
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.html
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.ts
  src/app/forms/components/govuk-form-group-textarea/govuk-form-group-textarea.component.html
  src/app/forms/custom-sections/adr-section/adr-section-edit/adr-section-edit.component.ts
  src/app/forms/custom-sections/tyres-section/tyres-section-edit/__tests__/tyres-section-edit.component.spec.ts
  src/app/forms/custom-sections/tyres-section/tyres-section-edit/tyres-section-edit.component.html
  src/app/forms/custom-sections/tyres-section/tyres-section-edit/tyres-section-edit.component.scss
  src/app/forms/custom-sections/tyres-section/tyres-section-edit/tyres-section-edit.component.ts
  src/app/forms/custom-sections/tyres-section/tyres-section-summary/tyres-section-summary.component.html
  src/app/forms/custom-sections/tyres-section/tyres-section-summary/tyres-section-summary.component.scss
  src/app/forms/custom-sections/tyres-section/tyres-section-summary/tyres-section-summary.component.ts
  src/app/forms/custom-sections/tyres-section/tyres-section-view/tyres-section-view.component.html
  src/app/forms/custom-sections/tyres-section/tyres-section-view/tyres-section-view.component.scss
  src/app/forms/custom-sections/tyres-section/tyres-section-view/tyres-section-view.component.ts
  src/app/forms/custom-sections/tyres-section/tyres-section.component.html
  src/app/forms/custom-sections/tyres-section/tyres-section.component.scss
  src/app/forms/custom-sections/tyres-section/tyres-section.component.ts
  src/app/forms/custom-sections/vehicle-section/vehicle-section-view/vehicle-section-view.component.html
  src/app/forms/custom-sections/weights-section/__tests__/weights-section-edit.component.spec.ts
  src/app/forms/custom-sections/weights-section/weights-section-edit/weights-section-edit.component.html
  src/app/forms/custom-sections/weights-section/weights-section-edit/weights-section-edit.component.scss
  src/app/forms/custom-sections/weights-section/weights-section-edit/weights-section-edit.component.ts
  src/app/forms/custom-sections/weights-section/weights-section-summary/weights-section-summary.component.html
  src/app/forms/custom-sections/weights-section/weights-section-summary/weights-section-summary.component.scss
  src/app/forms/custom-sections/weights-section/weights-section-summary/weights-section-summary.component.ts
  src/app/forms/custom-sections/weights-section/weights-section-view/weights-section-view.component.html
  src/app/forms/custom-sections/weights-section/weights-section-view/weights-section-view.component.scss
  src/app/forms/custom-sections/weights-section/weights-section-view/weights-section-view.component.ts
  src/app/forms/custom-sections/weights-section/weights-section.component.html
  src/app/forms/custom-sections/weights-section/weights-section.component.scss
  src/app/forms/custom-sections/weights-section/weights-section.component.ts
  src/app/forms/dynamic-forms.module.ts
  src/app/forms/validators/common-validators.service.ts
  src/app/models/options.model.ts
  src/app/store/technical-records/technical-record-service.actions.ts
  src/app/store/technical-records/technical-record-service.reducer.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
Labels: enhancement

#1738 fix(cb2-0000): turn off tyres and weights in int
  src/assets/featureToggle.int.json
Labels: bug

#1742 fix(CB2-16138): fix tank inspections heading on summary page
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.ts
Labels: bug

#1741 fix(CB2-16141): only show UN numbers that have changed
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.html
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.ts
Labels: bug

#1740 fix(CB2-16139): dispatch action to properly remove UN number from state
  src/app/forms/custom-sections/adr-section/adr-section-edit/adr-section-edit.component.ts
  src/app/store/technical-records/technical-record-service.actions.ts
  src/app/store/technical-records/technical-record-service.reducer.ts
Labels: bug
