Repository dvsa/cvs-app-vtm, pull requests merged in 2025-04, with the labels that each got.

#1836 feat(add-ids-to-defects-list): add testids
  src/app/features/test-records/components/test-type-select/test-type-select.component.html
  src/app/forms/components/defect-select/defect-select.component.html
  src/app/forms/components/required-standard-select/required-standard-select.component.html
Labels: enhancement

#1838 feat(CB2-16454): prewrap certificate notes
  src/app/forms/custom-sections/adr-section/adr-section-summary/adr-section-summary.component.html
  src/app/forms/custom-sections/adr-section/adr-section-view/adr-section-view.component.html
Labels: enhancement

#1845 chore(CB2-0000): bump version to 1.34
  package-lock.json
  package.json
Labels: task

#1846 feat(CB2-16786): hide prepare name and id for DBA tests
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-psv-hgv-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-default-trl-vehicle-section.template.ts
  src/app/forms/templates/test-records/section-templates/vehicle/desk-based-test-hgv-vehicle-section-group1And2And4.template.ts
Labels: enhancement

#1850 fix(CB2-17325): fix character length limit display
  src/app/forms/components/govuk-form-group-input/govuk-form-group-input.component.html
  src/app/forms/components/govuk-form-group-radio/govuk-form-group-radio.component.html
  src/app/forms/components/govuk-form-group-select/govuk-form-group-select.component.html
  src/app/forms/components/govuk-form-group-textarea/govuk-form-group-textarea.component.html
  src/app/forms/components/govuk-form-group-textarea/govuk-form-group-textarea.component.ts
Labels: bug

#1847 feat(CB2-16736): make trailer id appear as a license plate
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.html
  src/app/features/tech-record/components/tech-record-change-type/tech-record-change-type.component.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-title/__tests__/tech-record-title.component.spec.ts
  src/app/features/tech-record/components/tech-record-title/tech-record-title.component.html
  src/app/features/test-records/components/vehicle-header/vehicle-header.component.html
Labels: enhancement

#1848 feat(CB2-16747): fix spacing
  src/app/features/test-records/components/base-test-record/base-test-record.component.scss
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.html
  src/app/forms/components/dynamic-form-field/dynamic-form-field.component.ts
Labels: enhancement

#1854 feat(cb2-16962): VTM - Remove old form service from VTM ADR section
  src/app/features/tech-record/components/tech-record-summary-changes/__tests__/tech-record-summary-changes.component.spec.ts
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.html
  src/app/features/tech-record/components/tech-record-summary-changes/tech-record-summary-changes.component.ts
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.html
  src/app/features/tech-record/components/tech-record-summary/tech-record-summary.component.ts
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/__tests__/adr-examiner-notes-history.component-edit.spec.ts
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history-edit.component.html
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history.component-edit.scss
  src/app/forms/custom-sections/adr-examiner-notes-history-edit/adr-examiner-notes-history.component-edit.ts
  src/app/forms/custom-sections/adr-examiner-notes-history-view/__tests__/adr-examiner-notes-history-view.component.spec.ts
  src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.html
  src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.scss
  src/app/forms/custom-sections/adr-examiner-notes-history-view/adr-examiner-notes-history-view.component.ts
  src/app/forms/custom-sections/adr-new-certificate-required-view/__tests__/adr-new-certificate-required-view.component.spec.ts
  src/app/forms/custom-sections/adr-new-certificate-required-view/adr-new-certificate-required-view.component.html
  src/app/forms/custom-sections/adr-new-certificate-required-view/adr-new-certificate-required-view.component.scss
  src/app/forms/custom-sections/adr-new-certificate-required-view/adr-new-certificate-required-view.component.ts
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/__tests__/adr-permitted-dangerous-goods.component.spec.ts
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.html
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.scss
  src/app/forms/custom-sections/adr-permitted-dangerous-goods/adr-permitted-dangerous-goods.component.ts
  src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/__tests__/adr-tank-details-initial-inspection-view.component.spec.ts
  src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/adr-tank-details-initial-inspection-view.component.html
  src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/adr-tank-details-initial-inspection-view.component.scss
  src/app/forms/custom-sections/adr-tank-details-initial-inspection-view/adr-tank-details-initial-inspection-view.component.ts
  src/app/forms/custom-sections/adr-tank-details-m145-view/__tests__/adr-tank-details-m145-view.component.spec.ts
  src/app/forms/custom-sections/adr-tank-details-m145-view/adr-tank-details-m145-view.component.html
  src/app/forms/custom-sections/adr-tank-details-m145-view/adr-tank-details-m145-view.component.scss
  src/app/forms/custom-sections/adr-tank-details-m145-view/adr-tank-details-m145-view.component.ts
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-edit/__tests__/adr-tank-details-subsequent-inspections-edit.component.spec.ts
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-edit/adr-tank-details-subsequent-inspections-edit.component.html
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-edit/adr-tank-details-subsequent-inspections-edit.component.scss
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-edit/adr-tank-details-subsequent-inspections-edit.component.ts
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/__tests__/adr-tank-details-subsequent-inspections-view.component.spec.ts
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/adr-tank-details-subsequent-inspections-view.component.html
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/adr-tank-details-subsequent-inspections-view.component.scss
  src/app/forms/custom-sections/adr-tank-details-subsequent-inspections-view/adr-tank-details-subsequent-inspections-view.component.ts
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/__tests__/adr-tank-statement-un-number-edit.component.spec.ts
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.html
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.scss
  src/app/forms/custom-sections/adr-tank-statement-un-number-edit/adr-tank-statement-un-number-edit.component.ts
  src/app/forms/custom-sections/adr-tank-statement-un-number-view/__tests__/adr-tank-statement-un-number-view.component.spec.ts
  src/app/forms/custom-sections/adr-tank-statement-un-number-view/adr-tank-statement-un-number-view.component.html
  src/app/forms/custom-sections/adr-tank-statement-un-number-view/adr-tank-statement-un-number-view.component.scss
  src/app/forms/custom-sections/adr-tank-statement-un-number-view/adr-tank-statement-un-number-view.component.ts
  src/app/forms/custom-sections/adr/__tests__/adr.component.spec.ts
  src/app/forms/custom-sections/adr/adr.component.html
  src/app/forms/custom-sections/adr/adr.component.scss
  src/app/forms/custom-sections/adr/adr.component.ts
  src/app/forms/templates/general/adr-summary.template.ts
  src/app/forms/templates/general/adr.template.ts
  src/app/forms/utils/tech-record-constants.ts
  src/app/services/technical-record/technical-record-change.service.ts
  src/app/store/technical-records/__tests__/technical-record-service.effects.spec.ts
  src/assets/featureToggle.int.json
  src/assets/featureToggle.json
  src/assets/featureToggle.preprod.json
  src/assets/featureToggle.prod.json
Labels: enhancement
